CREATE OR REPLACE VIEW SWMS.V_BATCH_RESEQ_FLAG AS
SELECT route_batch_no, MAX(batch_reseq_flag) batch_reseq_flag
  FROM route
 GROUP BY route_batch_no;

CREATE OR REPLACE PUBLIC SYNONYM V_BATCH_RESEQ_FLAG FOR SWMS.V_BATCH_RESEQ_FLAG;
