CREATE OR REPLACE VIEW SWMS.V_DOD_LABEL_DETAIL AS 
SELECT DLD.ORDER_ID,
       M.CUST_ID,
       DLD.ORDER_LINE_ID,
       DLD.PROD_ID,
       DLD.ROUTE_NO,
       DLD.SRC_LOC,
       DLD.QTY_ALLOC,
       DLD.PALLET_ID,
       DLD.BATCH_NO,
       DLD.MAX_CASE_SEQ,
       DLD.START_SEQ,
       DLD.END_SEQ,
       DLD.PACK_DATE,
       DLD.EXP_DATE,
       DLD.LOT_ID,
       DLD.DOD_CUST_ITEM_BARCODE,
       DLD.DOD_FIC,
       DLD.ADD_DATE,
       DLD.ADD_USER, 
       DLD.UPD_DATE,
       DLD.UPD_USER
  FROM ORDM M, DOD_LABEL_DETAIL DLD
 WHERE M.ORDER_ID = DLD.ORDER_ID;

CREATE OR REPLACE PUBLIC SYNONYM V_DOD_LABEL_DETAIL
   FOR SWMS.V_DOD_LABEL_DETAIL;

GRANT ALL ON V_DOD_LABEL_DETAIL TO SWMS_USER;
GRANT SELECT ON V_DOD_LABEL_DETAIL TO SWMS_VIEWER;
