CREATE OR REPLACE VIEW SWMS.V_DOD_LABEL_DETAIL_BCKUP AS 
SELECT DLD.ORDER_ID,
       (SELECT CUST_ID FROM DOD_LABEL_HEADER_BCKUP WHERE ORDER_ID = DLD.ORDER_ID AND ROWNUM = 1) CUST_ID,
       DLD.ORDER_LINE_ID,
       DLD.PROD_ID,
       DLD.ROUTE_NO,
       DLD.SRC_LOC,
       DLD.QTY_ALLOC,
       DLD.PALLET_ID,
       DLD.BATCH_NO,
       DLD.MAX_CASE_SEQ,
       DLD.START_SEQ,
       DLD.END_SEQ,
       DLD.PACK_DATE,
       DLD.EXP_DATE,
       DLD.LOT_ID,
       DLD.DOD_CUST_ITEM_BARCODE,
       DLD.DOD_FIC,
       DLD.ADD_DATE,
       DLD.ADD_USER, 
       DLD.UPD_DATE,
       DLD.UPD_USER
  FROM DOD_LABEL_DETAIL_BCKUP DLD;

CREATE OR REPLACE PUBLIC SYNONYM V_DOD_LABEL_DETAIL_BCKUP
   FOR SWMS.V_DOD_LABEL_DETAIL_BCKUP;

GRANT ALL ON V_DOD_LABEL_DETAIL_BCKUP TO SWMS_USER;
GRANT SELECT ON V_DOD_LABEL_DETAIL_BCKUP TO SWMS_VIEWER;
