CREATE OR REPLACE FORCE VIEW swms.v_matrix_replen_list
AS
  SELECT DISTINCT repls.task_id,
                  repls.type,
                  repls.replen_type,
                  repls.replen_area,
                  repls.status,
                  repls.prod_id,
                  repls.cust_pref_vendor,
                  repls.pallet_id,
                  repls.src_loc,
                  repls.dest_loc,
                  repls.uom,
                  repls.dest_uom,
                  repls.qty,
                  repls.drop_qty,
                  repls.route_no,
                  repls.truck_no,
                  repls.door_no,
                  repls.order_id,
                  repls.float_no,
                  repls.exp_date,
                  repls.mfg_date,
                  repls.descrip,
                  repls.mfg_sku,
                  repls.d_pikpath,
                  repls.s_pikpath,
                  repls.miniload_storage_ind,
                  repls.area_code,
                  repls.src_pik_aisle,
                  repls.dest_pik_aisle,
                  repls.src_put_aisle,
                  repls.dest_put_aisle,
                  repls.src_put_slot,
                  repls.dest_put_slot,
                  repls.name,
                  repls.inv_dest_loc,
                  repls.route_batch_no,
                  repls.seq_no,
                  --last_stop.last_stop_no,
                  --last_stop.route_active,
                  repls.priority,
                  repls.case_no,
                  repls.mx_batch_no,
                  repls.print_lpn,
                  repls.rec_id,
                  repls.rec_date,
                  repls.inv_uom,
                  repls.pallet_type
  FROM
      (SELECT r.task_id,
              r.type,
              r.replen_type,
              r.replen_area,
              r.status,
              r.prod_id,
              r.cust_pref_vendor,
              r.pallet_id,
              r.src_loc,
              r.dest_loc,
              r.uom uom,
              dest.uom dest_uom,              
              CEIL (r.qty / p.spc) qty,
              NVL (r.drop_qty, 0) drop_qty,
              r.route_no,
              r.truck_no,
              r.door_no,
              r.order_id,
              r.float_no,
              r.exp_date,
              r.mfg_date,
              p.descrip,
              NVL (p.mfg_sku, '*') mfg_sku,
              dest.pik_path d_pikpath,
              src.pik_path s_pikpath,
              p.miniload_storage_ind,
              sa.area_code,
              src.pik_aisle src_pik_aisle,
              dest.pik_aisle dest_pik_aisle,
              src.put_aisle src_put_aisle,
              dest.put_aisle dest_put_aisle,
              src.put_slot src_put_slot,
              dest.put_slot dest_put_slot,
              ai.name,
              r.inv_dest_loc,
              NVL (r1.route_batch_no, 0) route_batch_no,
              NVL (r1.seq_no, 0) seq_no,
              r.priority,
              r.case_no,
              r.mx_batch_no,
              NVL(r.print_lpn, 'N') print_lpn,
              r.rec_id,
              NVL(i.rec_date, SYSDATE) rec_date,
              i.inv_uom,
              src.pallet_type
         FROM route r1,
              swms.swms_sub_areas sa,
              swms.aisle_info ai,
              swms.loc src,
              swms.loc dest,
              swms.pm p,
              swms.replenlst r,
              inv i 
        WHERE r.type IN (SELECT DISTINCT matrix_task_type FROM  matrix_task_priority)
          AND r.status  = 'NEW'
          AND r.user_id IS NULL
          AND i.logi_loc(+) = r.pallet_id        
          AND p.prod_id = r.prod_id
          AND p.cust_pref_vendor = r.cust_pref_vendor
          AND src.logi_loc = r.src_loc
          AND r.dest_loc IS NOT NULL
          AND NVL (r.inv_dest_loc, r.dest_loc) = dest.logi_loc         
          AND ai.pick_aisle = dest.pik_aisle        
          AND r.route_no       = r1.route_no (+)
          AND sa.sub_area_code = ai.sub_area_code ) repls
    ;