CREATE OR REPLACE VIEW SWMS.V_SWMS_SESSION AS
SELECT S.SID, S.SERIAL#, S.USERNAME,
       SUBSTR(S.MODULE,1,DECODE(INSTR(S.MODULE,' '),0,LENGTH(S.MODULE),INSTR(S.MODULE,' ')-1)) MODULE,
       STATUS, MACHINE, TO_CHAR(LOGON_TIME,'DD-MON-YY HH24:MI') LOGON_TIME,
       (SELECT COUNT(*) FROM DBA_DML_LOCKS L WHERE L.SESSION_ID = S.SID) LOCK_COUNT,
       TO_CHAR(TO_DATE((SELECT MIN(L.LAST_CONVERT) FROM DBA_DML_LOCKS L WHERE L.SESSION_ID = S.SID),'sssss'),'HH24:MI:SS') NEWEST_LOCK,
       TO_CHAR(TO_DATE((SELECT MAX(L.LAST_CONVERT) FROM DBA_DML_LOCKS L WHERE L.SESSION_ID = S.SID),'sssss'),'HH24:MI:SS') OLDEST_LOCK,
       S.BLOCKING_SESSION BLOCKER_SID,
       DECODE(BLKER.SID,NULL,DECODE(BLKEE.SID,NULL,NULL,'BLOCKEE'),DECODE(BLKEE.SID,NULL,'BLOCKER','BOTH')) TROUBLE,
       DECODE(BLKER.SID,NULL,DECODE(BLKEE.SID,NULL,4,3),DECODE(BLKEE.SID,NULL,1,2)) TROUBLE_SORT
  FROM V$SESSION S,
       (SELECT DISTINCT SID FROM V$LOCK WHERE BLOCK = 1) BLKER,
       (SELECT DISTINCT SID FROM V$LOCK WHERE REQUEST > 0) BLKEE
 WHERE BLKER.SID(+) = S.SID
   AND BLKEE.SID(+) = S.SID
   AND (S.PROGRAM LIKE 'frmweb%' or (S.MODULE IS NOT NULL AND S.USERNAME IS NOT NULL))
 ORDER BY TROUBLE_SORT, LOCK_COUNT DESC, LOGON_TIME;
