CREATE OR REPLACE PACKAGE swms.pl_swms_error_codes
IS
	NORMAL			CONSTANT NUMBER := 0;     -- Normal
	FOUND			CONSTANT NUMBER := 0;     -- record found
	NOR_CLUSTER		CONSTANT NUMBER := 1;     -- Normal cluster
	RESUME_NOR		CONSTANT NUMBER := 2;     -- Normal resume
	RESUME_CLS		CONSTANT NUMBER := 3;     -- Cluster resume
	MORE_TASK		CONSTANT NUMBER := 4;     -- More task
	NORMAL_CONSOL		CONSTANT NUMBER := 5;     -- Normal consolidation
	CONFIRM			CONSTANT NUMBER := 6;     -- need to confirm
	NORMAL_KIT		CONSTANT NUMBER := 7;     -- Normal kitting
	LAST_ONE		CONSTANT NUMBER := 8;     -- last task
	QA_SAMPLE		CONSTANT NUMBER := 9;     -- QA Sample
	QTY_OVER		CONSTANT NUMBER := 10;    -- Qty OVER
	UPDATE_FAIL		CONSTANT NUMBER := 11;    -- update fail
	INSERT_FAIL		CONSTANT NUMBER := 12;    -- insert fail
	MORE_PICK		CONSTANT NUMBER := 13;    -- more pick task
	DROP_FULL		CONSTANT NUMBER := 14;    -- drop full tote
	RF_WAIT			CONSTANT NUMBER := 20;    -- For server use only
	CLOSED			CONSTANT NUMBER := 21;    -- file already closed
	OPENED			CONSTANT NUMBER := 22;    -- file already open
	NEW			CONSTANT NUMBER := 23;    -- new file
	NOT_FOUND		CONSTANT NUMBER := 24;    -- record not found/no more task
	UN_AUTH			CONSTANT NUMBER := 25;    -- un-authorized user
	ALRDY_EXIST		CONSTANT NUMBER := 26;    -- file/record already exist
	BAD_REC			CONSTANT NUMBER := 27;    -- bad record/label
	WAIT			CONSTANT NUMBER := 28;    -- Wait for manager
	INV_OPT			CONSTANT NUMBER := 29;    -- invalid operation
	BLD_REC			CONSTANT NUMBER := 30;    -- blind receiving
	INV_LOCATION		CONSTANT NUMBER := 31;    -- invalid location
	CONSOL_FIRST		CONSTANT NUMBER := 32;    -- need to consolidate first
	NEED_REPLEN		CONSTANT NUMBER := 33;    -- need replenish
	NEED_CONTAINER		CONSTANT NUMBER := 34;    -- need container/destination label
	INV_PASSWD		CONSTANT NUMBER := 35;    -- invalid passwd
	INVALID_UOM		CONSTANT NUMBER := 36;    -- invalid UOM
	INV_PRODID		CONSTANT NUMBER := 37;    -- Invalid Product ID
	NO_MORE_TASK		CONSTANT NUMBER := 38;    -- No more task required for function
	INV_LABEL		CONSTANT NUMBER := 39;    -- Invalid label
	LABEL_USED		CONSTANT NUMBER := 40;    -- Lable used by others
	INV_PUTLST		CONSTANT NUMBER := 41;    -- Invalid putaway list
	INV_PUTQTY		CONSTANT NUMBER := 42;    -- Invalid putaway Qty
	NEED_UNLOAD		CONSTANT NUMBER := 43;    -- need to unload
	SHIP_ALREADY		CONSTANT NUMBER := 44;    -- shipped already
	QTY_TOO_LARGE		CONSTANT NUMBER := 45;    -- Qty Too Large
	NEED_LABEL		CONSTANT NUMBER := 46;    -- need label before shipping
	FULL			CONSTANT NUMBER := 47;    -- Box Full
	BAD_SER			CONSTANT NUMBER := 48;    -- Bad Serial Number
	BAD_TRANS		CONSTANT NUMBER := 49;    -- Bad Transaction
	INV_LOT			CONSTANT NUMBER := 50;    -- Invalid Lot
	REC_COMP		CONSTANT NUMBER := 51;    -- Receipt Completed
	MORE_INFO		CONSTANT NUMBER := 52;    -- need more infomation
	INV_LANE		CONSTANT NUMBER := 53;    -- Invalid Lane ID
	INV_REC_STATUS		CONSTANT NUMBER := 54;    -- Invalid Receiving Status
	ALRDY_CHKIN		CONSTANT NUMBER := 55;    -- Already checked in
	INV_CODE		CONSTANT NUMBER := 56;    -- Invalid Code
	INV_AISLE		CONSTANT NUMBER := 57;    -- Invalid Aisle
	INV_ORDER		CONSTANT NUMBER := 58;    -- Invalid Order ID
	NO_CARR			CONSTANT NUMBER := 59;    -- No Carrier found
	QTY_TOO_SMALL		CONSTANT NUMBER := 60;    -- Qty too small, upd_inv
	NOT_RELEASE		CONSTANT NUMBER := 61;    -- NOt realease, loading
	SERIAL			CONSTANT NUMBER := 62;    -- Serialized items, upd_inv
	NEED_2_TOTE		CONSTANT NUMBER := 63;    -- need two container labels
	NEED_PACKTOTE		CONSTANT NUMBER := 64;    -- need pack tote label
	QTY_NOT_MATCH		CONSTANT NUMBER := 65;    -- qty not match
	NOT_DONE_PIK		CONSTANT NUMBER := 66;    -- Not finished picking
	NOT_PIK_YET		CONSTANT NUMBER := 67;    -- Not pick yet
	INV_ZONE		CONSTANT NUMBER := 68;    -- Invalid Zone
	ZONE_NOT_FOUND		CONSTANT NUMBER := 69;    -- Zone Not done
	INV_SRC_LABEL		CONSTANT NUMBER := 70;    -- Invalid Src label
	INV_DEST_LABEL		CONSTANT NUMBER := 71;    -- Invalid Dest label
	INV_SRC_LOCATION	CONSTANT NUMBER := 72;    -- Invalid Src location
	INV_DEST_LOCATION	CONSTANT NUMBER := 73;    -- Invalid Dest location
	INV_LOAD		CONSTANT NUMBER := 74;    -- Invalid Load
	DATA_ERROR		CONSTANT NUMBER := 80;    -- Data Error in DataBase
	NEED_RECONC		CONSTANT NUMBER := 81;    -- Receipt need to be reconciled
	CHILD_LABEL		CONSTANT NUMBER := 82;    -- Child label
	PACK_FIRST		CONSTANT NUMBER := 83;    -- pack before print shipping label
	INV_WHSE		CONSTANT NUMBER := 84;    -- Invalid Warehouse
	WEIGHT_OUT_OF_RANGE	CONSTANT NUMBER := 85;    -- Weight out of range
	NO_RF			CONSTANT NUMBER := 86;    -- No RF for confirm putaway
	WRONG_PUT		CONSTANT NUMBER := 87;    -- Wrong putaway slot
	INV_SLOT		CONSTANT NUMBER := 88;    -- Invalid slot
	INV_PO			CONSTANT NUMBER := 90;    -- Invalid Purchase Order
	CLO_PO			CONSTANT NUMBER := 91;    -- PO is already closed
	MORE_REC_DATA		CONSTANT NUMBER := 92;    -- more receiving data are needed
	HOME_SLOT		CONSTANT NUMBER := 93;    -- Home slot assigned
	PUT_DONE		CONSTANT NUMBER := 94;    -- already putaway
	INV_AREA		CONSTANT NUMBER := 95;    -- Invalid area
	NO_TASK			CONSTANT NUMBER := 96;    -- No task selected
	NOT_HOME_SLOT		CONSTANT NUMBER := 97;    -- Not a home slot
	QTY_ENOUGH		CONSTANT NUMBER := 98;    -- Enough quantity for dest_slot
	SIZE_ERROR		CONSTANT NUMBER := 99;    -- Pallet Type Change not permitted during transfer.
	ERR_ALLOC		CONSTANT NUMBER := 100;   -- Qty allocated from slot. Transfer not permitted.
	LOC_ERROR		CONSTANT NUMBER := 101;   -- Location mismatch or damaged loc during swap.
	QTY_ERROR		CONSTANT NUMBER := 102;   -- Slot has alloc/planned qty. Cannot modify qty.
	CASE_HOME_EMPTY		CONSTANT NUMBER := 103;   -- Case home slot empty
	EXTEND_PO		CONSTANT NUMBER := 104;   -- Cannot close an extended PO.
	WRONG_EQUIP		CONSTANT NUMBER := 105;   -- Wrong Equipment for the specified RF operation
	LOC_QTYEXP_WARN		CONSTANT NUMBER := 106;   -- Case stock transfer to a LOC with qty expected , syspar = warn
	LOC_QTYEXP_PRVN		CONSTANT NUMBER := 107;   -- Case stock transfer to a LOC with qty expected , syspar = prevent
	NO_STKXFER_SYSPAR	CONSTANT NUMBER := 108;   -- Case stock transfer to a LOC with qty expected , w/o syspar in sys_config
	ITEM_NOCOST_WARN	CONSTANT NUMBER := 109;   -- Case stock qty adjust w/o item cost, syspar = warn
	ITEM_NOCOST_PRVN	CONSTANT NUMBER := 110;   -- Case stock qty adjust w/o item cost, syspar = prevent
	ITEM_NOCOST_SYSPAR	CONSTANT NUMBER := 111;   -- Case stock qty adjust w/o item cost, without syspar in sys_config
	LOCK_PO			CONSTANT NUMBER := 112;   -- Case when PO is in Use by another user during RF close PO program
	UNAVL_PO		CONSTANT NUMBER := 113;   -- PO is not available
	INV_PUTAWAY_OPT		CONSTANT NUMBER := 116;   -- Invalid Putaway option
	INV_UPDATE_FAIL		CONSTANT NUMBER := 118;   -- Update of INV table failed
	ERM_UPDATE_FAIL		CONSTANT NUMBER := 119;   -- Update of ERM table failed
	ERD_UPDATE_FAIL		CONSTANT NUMBER := 120;   -- Update of ERD table failed
	PM_UPDATE_FAIL		CONSTANT NUMBER := 121;   -- Update of PM table failed
	SYSCFG_UPDATE_FAIL	CONSTANT NUMBER := 122;   -- Update of SYS_CONFIG table failed
	DEL_PUTAWYLST_FAIL	CONSTANT NUMBER := 123;   -- Delete from PUTAWAYLST table failed
	SEL_SYSCFG_FAIL		CONSTANT NUMBER := 124;   -- Select from SYS_CONFIG table failed
	USE_SWAP		CONSTANT NUMBER := 125;   -- Case in HSM when attempting to transfer to a Home Slot
	EXP_DATE_INFO		CONSTANT NUMBER := 126;   -- Need expiration date information
	MFG_DATE_INFO		CONSTANT NUMBER := 127;   -- Need manufacturing date information
	QTY_NOT_ENOUGH		CONSTANT NUMBER := 128;   -- Qty not enough in transfers
	LOAD_FAIL		CONSTANT NUMBER := 129;   -- Program load on the Host failed
	DB_CONN_ERR		CONSTANT NUMBER := 130;   -- Cannot connect to database
	ALRDY_LOCATED		CONSTANT NUMBER := 131;   -- Aisle already located
	HOME_SLOT_UNAVL		CONSTANT NUMBER := 132;   -- Home Slot not available
	USE_ADJUST		CONSTANT NUMBER := 133;   -- User must use adjust instead of Locate screen on the RF
	TRN_UPDATE_FAIL		CONSTANT NUMBER := 134;   -- Update of TRANS table failed
	RPL_UPDATE_FAIL		CONSTANT NUMBER := 135;   -- Update of REPLENLST table failed
	DEL_IND_FAIL		CONSTANT NUMBER := 136;   -- Delete of IND transaction failed
	NOT_RES_LOC_CO		CONSTANT NUMBER := 137;   -- Not a Reserve locator company
	RES_LOC_CO		CONSTANT NUMBER := 138;   -- Reserve locator company
	RLC_ITEM_EXP_OR_FIFO	CONSTANT NUMBER := 139;   -- Not a Reserve locator company
	DEL_DLD_FAIL		CONSTANT NUMBER := 140;   -- Delete of DEMANDLST failed
	PUTAWAY_FAIL		CONSTANT NUMBER := 141;   -- SLMS dummy putaway failed
	SIZE_ERROR_WARN		CONSTANT NUMBER := 142;   -- allow transfer on pallet type mismatch and display warning
	LM_NO_ACTIVE_BATCH	CONSTANT NUMBER := 143;   -- User Without Active Batch (Labor)
	CTE_RTN_BTCH_FLG_OFF	CONSTANT NUMBER := 144;   -- Create Return Put Batch Flag Off
	LM_BATCH_UPD_FAIL	CONSTANT NUMBER := 145;   -- Could not update Labor Mgmt Batch
	NO_LM_BATCH_FOUND	CONSTANT NUMBER := 146;   -- Could not find a Labor Mgmt Batch
	PALLET_ON_HOLD		CONSTANT NUMBER := 147;   -- Pallet on hold -- Unavailable
	NEED_EXPMFG_DATE_INFO	CONSTANT NUMBER := 148;   -- Need expiration/manufactures date
	NO_LM_RTN_IND_JBCD	CONSTANT NUMBER := 149;   -- No Labor Return indirect job code
	LM_JOBCODE_NOT_FOUND	CONSTANT NUMBER := 150;   -- Unable to find LM jobcode
	LM_SCHED_NOT_FOUND	CONSTANT NUMBER := 151;   -- Unable to find LM schedule type
	LM_BATCH_COMPLETED	CONSTANT NUMBER := 152;   -- LM batch already completed
	LM_ACTIVE_BATCH		CONSTANT NUMBER := 153;   -- LM batch already active
	NO_LM_PARENT_FOUND	CONSTANT NUMBER := 154;   -- Could not find a LM Parent Batch
	LM_PARENT_UPD_FAIL	CONSTANT NUMBER := 155;   -- Count not update LM Parent Batch
	LM_BAD_USER		CONSTANT NUMBER := 156;   -- Either user id or labor group is invalid
	LM_INS_ISTART_FAIL	CONSTANT NUMBER := 157;   -- Unable to insert ISTART LM batch
	LM_INS_ISTOP_FAIL	CONSTANT NUMBER := 158;   -- Unable to insert ISTOP LM batch
	LM_MERGE_BATCH		CONSTANT NUMBER := 159;   -- LM batch already merged
	LOC_DAMAGED		CONSTANT NUMBER := 160;   -- Location is Damaged
	INV_INSERT_FAILED	CONSTANT NUMBER := 161;   -- Insert into INV table failed
	LOC_INSERT_FAILED	CONSTANT NUMBER := 162;   -- Insert into LOC table failed
	TRANS_INSERT_FAILED	CONSTANT NUMBER := 163;   -- Insert into TRANS table failed
	PM_INSERT_FAILED	CONSTANT NUMBER := 164;   -- Insert into PM table failed
	RPL_INSERT_FAILED	CONSTANT NUMBER := 165;   -- Insert into REPLENLST table failed
	DLD_INSERT_FAILED	CONSTANT NUMBER := 166;   -- Insert into DEMANDLST table failed
	CC_INSERT_FAILED	CONSTANT NUMBER := 167;   -- Insert into CC table failed
	WEIGHT_INSERT_FAILED	CONSTANT NUMBER := 168;   -- Insert into TMP_WEIGHT table failed
	NO_ERR_MSG_FOUND	CONSTANT NUMBER := 169;   -- No error msg in RF_ERROR_MESSAGES tab
	INV_XFR_LABEL		CONSTANT NUMBER := 170;   -- Invalid pallet during stock transer
	LOC_UPDATE_FAILED	CONSTANT NUMBER := 171;   -- Update to LOC table failed
	CC_UPDATE_FAILED	CONSTANT NUMBER := 172;   -- Update to CC table failed
	PUTAWAYLST_UPDATE_FAIL	CONSTANT NUMBER := 173;   -- Update of PUTAWAYLST table failed
	INVALID_EXP_DATE	CONSTANT NUMBER := 174;   -- ORA date error when updating exp date
	INVALID_MFG_DATE	CONSTANT NUMBER := 175;   -- ORA date error when updating mfg date
	DEL_INV_FAIL		CONSTANT NUMBER := 176;   -- Delete from INV table failed.
	SEL_INV_FAIL		CONSTANT NUMBER := 177;   -- Select from INV table failed.
	SEL_LOC_FAIL		CONSTANT NUMBER := 178;   -- Select from LOC table failed.
	SEL_RPL_FAIL		CONSTANT NUMBER := 179;   -- Select from REPLENLST table failed.
	SEL_DLD_FAIL		CONSTANT NUMBER := 180;   -- Select from DEMANDLST table failed.
	SEL_PUTAWAYLST_FAIL	CONSTANT NUMBER := 181;   -- Select from PUTAWAYLST table failed.
	DEL_RPL_FAIL		CONSTANT NUMBER := 182;   -- Delete from REPLENLST table failed.
	DEL_TRANS_FAIL		CONSTANT NUMBER := 183;   -- Delete from TRANS table failed.
	DLD_UPDATE_FAIL		CONSTANT NUMBER := 184;   -- Update of DEMANDLST table failed.
	LM_PT_DIST_BAD_SETUP	CONSTANT NUMBER := 185;   -- LM Point Distance not setup.
	LM_BAY_DIST_BAD_SETUP	CONSTANT NUMBER := 186;   -- LM Bay Distance not setup.
	CROSS_AISLE_SEL_FAIL	CONSTANT NUMBER := 187;   -- Select of cross aisle failed for LM.
	LM_FORKLIFT_NOT_FOUND	CONSTANT NUMBER := 188;   -- Forklift labor function missing.
	LM_FORKLIFT_NOT_ACTIVE	CONSTANT NUMBER := 189;   -- Forklift labor func. not active.
	LM_SUSP_BATCH_ACTV	CONSTANT NUMBER := 190;   -- Suspended LM batch activated.
	LM_INS_FL_DFLT_FAIL	CONSTANT NUMBER := 191;   -- Insert Forklift Ind. batch fail.
	PENDING_RPL_TSK_FAIL	CONSTANT NUMBER := 192;   -- Failed to get pending rpl tasks.
	UPCINFO_INSERT_FAILED	CONSTANT NUMBER := 193;   -- Insert into UPCINFO table failed
	UPCINFO_UPDATE_FAILED	CONSTANT NUMBER := 194;   -- Update of UPCINFO table failed
	UPCINFO_SELECT_FAILED	CONSTANT NUMBER := 195;   -- Select from UPCINFO table failed
	LM_PT_DIST_BADSETUP_WTW	CONSTANT NUMBER := 196;   -- LM Point Distance not setup. W to W
	LM_PT_DIST_BADSETUP_WFD	CONSTANT NUMBER := 197;   -- LM Point Distance not setup. W to First door
	LM_PT_DIST_BADSETUP_DTD	CONSTANT NUMBER := 198;   -- LM Point Distance not setup. door to door
	LM_PT_DIST_BADSETUP_DTA	CONSTANT NUMBER := 199;   -- LM Point Distance not setup. door to aisle
	LM_PT_DIST_BADSETUP_ATA	CONSTANT NUMBER := 200;   -- LM Point Distance not setup. aisle to aisle
	LM_PT_DIST_BADSETUP_ACA	CONSTANT NUMBER := 201;   -- LM Point Distance not setup. Cross aisle to aisle
	LM_PT_DIST_BADSETUP_NCA	CONSTANT NUMBER := 202;   -- LM Point Distance not setup. Next Cross aisle to aisle
	LM_PT_DIST_BADSETUP_WFA	CONSTANT NUMBER := 203;   -- LM Point Distance not setup. Warehouse to first aisle
	LM_PT_DIST_BADSETUP_PT	CONSTANT NUMBER := 204;   -- Point Type not setup.
	MOV_UPDATE_FAIL		CONSTANT NUMBER := 205;   -- Update of WHMVELOC table failed
	MOVED_ALREADY		CONSTANT NUMBER := 206;   -- Pallet/Location moved already
	NO_PICK_SLOT_FOUND	CONSTANT NUMBER := 207;   -- No Pick slot found for reserve move
	FLOATING_SLOT_MOVE	CONSTANT NUMBER := 208;   -- Reserve pallet belongs to Floating SLOT
	USE_RESERVE_MOVE	CONSTANT NUMBER := 209;   -- Used reserve move from the pick menu
	ITEM_WO_ZONE		CONSTANT NUMBER := 210;   -- Move item had no zone in pm
	ITEM_WO_NEW_ZONE	CONSTANT NUMBER := 211;   -- Move item had no new zone
	RSRV_SLOT_UNAVL		CONSTANT NUMBER := 212;   -- Reserve Slot not available
	MOVPLT_IN_NEW_WH_WARN	CONSTANT NUMBER := 213;   -- Move pallet exists in new WH, WARN
	MIN_PATH_FAILED		CONSTANT NUMBER := 214;   -- Select of put_path for min loc failed
	INP_PATH_FAILED		CONSTANT NUMBER := 215;   -- Select of put_path for inp loc failed
	MAX_PATH_FAILED		CONSTANT NUMBER := 216;   -- Select of put_path for max loc failed
	INV_FLOAT_RANGE		CONSTANT NUMBER := 217;   -- Invalid float range during WH move
	LM_MULTI_ACTIVE_BATCH	CONSTANT NUMBER := 218;   -- Multiple active batches found for user
	LM_N_STATUS_BATCH	CONSTANT NUMBER := 219;   -- LM N status batch(es) found for user
	FLOAT_TRANSFER		CONSTANT NUMBER := 220;   -- Reserve pallet belongs to Floating SLOT
	USE_TRANSFER		CONSTANT NUMBER := 221;   -- RF's sent wrong option to the Host
	XFR_AVL_SLOT_FAIL	CONSTANT NUMBER := 222;   -- Look up of available transfer slot fail
	INVALID_HRV_DATE	CONSTANT NUMBER := 223;   -- Invalid harvest date during data coll
	HRV_DATE_WARN		CONSTANT NUMBER := 224;   -- Harvest date warning during data coll
	SEL_TRN_FAIL		CONSTANT NUMBER := 225;   -- Select from TRANS table failed.
	SEL_SEQ_FAIL		CONSTANT NUMBER := 226;   -- Select from oracle sequencer failed
	SEL_ERM_FAIL		CONSTANT NUMBER := 227;   -- Select from ERM table failed
	SEL_AGING_FAIL		CONSTANT NUMBER := 228;   -- Select from AGING_ITEMS table failed
	NEED_AGING		CONSTANT NUMBER := 229;   -- Item need to be aged
	INV_EXT_UPC		CONSTANT NUMBER := 230;   -- Invalid external UPC entered from RF
	MLT_FLOATING_SLOT_MOVE	CONSTANT NUMBER := 231;   -- Reserve pallet belongs to multiple Floating SLOT
	SEL_PROCESS_LOG_FAIL	CONSTANT NUMBER := 232;   -- Select from Process_log table failed.
	REPLEN_DONE		CONSTANT NUMBER := 233;   -- Demand Replenishment already done
	REC_LOCK_BY_OTHER	CONSTANT NUMBER := 234;   -- Record is locked by another user.
	USER_ALREADY_SIGNED_ON	CONSTANT NUMBER := 235;   -- User is already signed on another RF
	MAN_NOT_FOUND		CONSTANT NUMBER := 241;
	PAL_DMG_NO_TBATCH	CONSTANT NUMBER := 268;	  -- Cannot close damage return TBatch
	LM_GET_FORKLIFT_POINT	CONSTANT NUMBER := 270;   -- Get Forklift Point
	LM_INS_IND_FAIL		CONSTANT NUMBER := 271;   -- Insert Indirect Batch Fail
	LM_INV_FORK_POINT	CONSTANT NUMBER := 272;   -- Invalid Forklift Point
	LM_INV_BATCH_NO		CONSTANT NUMBER := 273;   -- Invalid Batch Number
	LM_INV_LBR_GRP		CONSTANT NUMBER := 274;   -- Invalid Labor Group
	LM_UPD_BATCH_FAIL	CONSTANT NUMBER := 275;   -- Update Batch Fail
	LM_INV_MASTER_BATCH	CONSTANT NUMBER := 276;   -- Invalid Master Batch Number
	LM_INV_SECOND_BATCH	CONSTANT NUMBER := 277;   -- Invalid Second Batch Number
	LM_BATCH_SAME		CONSTANT NUMBER := 278;   -- Master and Second Batch Same
	LM_MERGE_FAIL		CONSTANT NUMBER := 279;   -- Merge Batch Fail
	LM_BATCH_NOT_READY	CONSTANT NUMBER := 280;   -- Batch Not Ready To Work On
	LM_FORKLIFT_BATCH	CONSTANT NUMBER := 281;   -- Forklift Batch. Cannot be Signed On
	LM_ISTART_EXIST		CONSTANT NUMBER := 282;   -- ISTART already exist for the user
	LM_DUR_EXIST		CONSTANT NUMBER := 283;   -- Duration Exist
	LM_BATCH_NOT_EXIST	CONSTANT NUMBER := 284;   -- Batch Not Exist
	LM_NO_DIRECT_BATCH	CONSTANT NUMBER := 285;   -- No Direct Batch Exist
	LM_COMPLETE_BATCH	CONSTANT NUMBER := 286;   -- Batch is already complete
	LM_UN_AUTH_JOBCODE	CONSTANT NUMBER := 287;   -- Unauthorized Job code
	LM_LOT_BATCH		CONSTANT NUMBER := 288;   -- LOT Batch
	LM_INVALID_PASSWORD	CONSTANT NUMBER := 289;   -- Invalid Password on Indirect batch
	LM_INVALID_JOB_CODE	CONSTANT NUMBER := 290;   -- Invalid Job Code on Indirect batch
	LM_INVALID_USERID	CONSTANT NUMBER := 291;   -- Invalid User ID
	LM_MERGED_BATCH		CONSTANT NUMBER := 292;   -- Batch is already merged
	LM_FORKLIFT_FAIL	CONSTANT NUMBER := 293;   -- Forklift Sign off Failed
	INV_REC_LOCKED		CONSTANT NUMBER := 294;   -- Inventory Record Locked
	INV_INVOICE_NO		CONSTANT NUMBER := 295;   -- Invalid Invoice # input
	INV_TEMPERATURE		CONSTANT NUMBER := 296;   -- Invalid Temperature input
	NO_MSKU_DEEP		CONSTANT NUMBER := 297;   -- MSKU Pallet cannot be transferred to a deep slot
	MSKU_PLT_EXISTS		CONSTANT NUMBER := 298;   -- Cannot transfer pallet to location where MSKU pallet exists
	MSKU_PLT_QTY		CONSTANT NUMBER := 299;   -- MSKU license plate can have quantity 0 or 1.  (During Inventory Adjustment)
	MSKU_REP_PIK		CONSTANT NUMBER := 300;   -- Cannot Pick MSKU pallet since there is a pending replenishment task for NON MSKU pallet
	MSKU_PUTPIK		CONSTANT NUMBER := 301;   -- Cannot Pick MSKU pallet since there is a pending put away task for NON MSKU
	NON_MKSU_REP_PIK	CONSTANT NUMBER := 302;   -- Cannot Pick pallet since there is a pending replenishment task for MSKU pallet
	NON_MKSU_PUR_PIK	CONSTANT NUMBER := 303;   -- Cannot Pick pallet since there is a pending put away task for MSKU pallet
	SKU_LP_NOT_FOUND	CONSTANT NUMBER := 304;   -- Invalid MSKU license
	CANNOT_DIVIDE_MSKU	CONSTANT NUMBER := 305;   -- MSKU pallet cannot be divided since it has already been put away
	SEL_ERD_LPN_FAIL	CONSTANT NUMBER := 306;   -- Unable to select from ERD_LPN table
	CHILD_FETCH_FAIL	CONSTANT NUMBER := 307;   -- Unable to select child records for a parent pallet
	CHILD_ADJ_STATUS_FAIL	CONSTANT NUMBER := 308;   -- Unable to update status of all child pallets in MSKU pallet
							  -- since error in status of one or more child pallets
	NO_MSKU_FULL		CONSTANT NUMBER := 309;   -- MSKU Pallet can not be transferred to a slot having full pallet(s)
	MSKU_LP			CONSTANT NUMBER := 310;   -- pallet is a MSKU pallet and can not be handled by the program
	MSKU_SUB_FAILED		CONSTANT NUMBER := 311;   -- pallet substitution failed for a license plate in an MSKU pallet
	NOT_MSKU_LP		CONSTANT NUMBER := 312;   -- Regular LP scanned in MSKU Putaway mode
	LOC_HAS_MSKU		CONSTANT NUMBER := 313;   -- Location has Msku pallet. Use different Location.
	LOSSPREV_EXIST		CONSTANT NUMBER := 319;   -- Indicates scan loss has been recorded for the LP
	LOSSPREV_CREATED	CONSTANT NUMBER := 320;   -- Indicates scan loss  record created for this LP
	OSD_PENDING		CONSTANT NUMBER := 322;   -- The SN/PO is in pending status
	OSD_LOC_NOT_FOUND	CONSTANT NUMBER := 323;   -- No location found to putaway damage qty
	OSD_LOC_FOUND		CONSTANT NUMBER := 324;   -- Location found to putaway damage qty
	OSD_REC_NOT_FOUND	CONSTANT NUMBER := 325;   -- No record found in osd table
	OSD_RSN_CODE_ASND	CONSTANT NUMBER := 326;   -- OSD damage reason code assigned
	OSD_INS_FAILED		CONSTANT NUMBER := 327;   -- Insert OSD record failed
	OSD_UPD_FAILED		CONSTANT NUMBER := 328;   -- Update OSD record failed
	OSD_DEL_FAILED		CONSTANT NUMBER := 329;   -- Delete OSD record failed
	OSD_SEL_FAILED		CONSTANT NUMBER := 330;   -- Select OSD record failed
	DFT_QUEUE_NOT_FOUND	CONSTANT NUMBER := 331;   -- Default user print queue is not found
	SEL_RFINFO_FAIL		CONSTANT NUMBER := 332;   -- Select from rfinfo table failed.
	MSKU_LP_LIMIT_WARN	CONSTANT NUMBER := 336;   -- LP count exceeds NUM_MSKU_PALLETS to receive or putaway - warning - must be sub-divided
	MSKU_SUBDIV_LIMIT	CONSTANT NUMBER := 337;   -- LP count exceeds NUM_SUBDIV_PALLETS to subdivide
	MSKU_LP_LIMIT_ERROR	CONSTANT NUMBER := 338;   -- LP count exceeds NUM_MSKU_PALLETS - this is a fatal error
	RDC_ITEM		CONSTANT NUMBER := 339;   -- The item is a RDC item
	ITEM_SN_EXISTS		CONSTANT NUMBER := 340;   -- The item has a NEW or OPN SN
	COOL_MUST_VERIFY	CONSTANT NUMBER := 341;   -- Must verify COO labeling
	COOL_MUST_COLLECT	CONSTANT NUMBER := 342;   -- Must collect COO data before continuing
	RETURN_EXISTED		CONSTANT NUMBER := 343;   -- Return already existed
	INV_RETURN_EXISTED	CONSTANT NUMBER := 344;   -- A return existed of this invoice
	INVALID_REPLEN_TYPE	CONSTANT NUMBER := 345;   -- Invalid replenishment type
	OK_TO_PRINT		CONSTANT NUMBER := 346;   -- Manifest tripped and ready to print
	NO_PRINTER_DEFINED	CONSTANT NUMBER := 347;   -- No printer defined for return label
	PRINTING_ERROR		CONSTANT NUMBER := 348;   -- Printing encountered error
	INVOICE_RETURNED	CONSTANT NUMBER := 349;   -- Entire invoice was returned
	UPDATE_NOT_ALLOWED	CONSTANT NUMBER := 350;   -- Rtn cannot be updated (putawayed)
	DELETE_NOT_ALLOWED	CONSTANT NUMBER := 351;   -- Rtn cannot be deleted (putawayed)
	MANIFEST_WAS_CLOSED	CONSTANT NUMBER := 352;   -- MF in CLS status - no more to do
	SEL_MNL_FAIL		CONSTANT NUMBER := 353;   -- Select from REPLENLST table failed.
	MUST_SCAN_UPC		CONSTANT NUMBER := 354;   -- MNL Replen - must scan UPC (>1 item in src_loc)
	MNL_DROP_FAIL		CONSTANT NUMBER := 355;   -- MNL Replen Drop failed
	LOGIN_FAIL		CONSTANT NUMBER := 356;   -- login failed and host supplied message in auth_msg
	LOGIN_WARN		CONSTANT NUMBER := 357;   -- login successful but host supplied msg in auth_msg
	ACC_DONE		CONSTANT NUMBER := 358;
	ACC_NOT_BEGIN		CONSTANT NUMBER := 359;
	TRACK_TRUCK_ACCESSORY	CONSTANT NUMBER := 360;
	DMD_RPL_FOUND_IN_SWP	CONSTANT NUMBER := 361;   -- Stop the swap when dmd rpl is found
	ML_INDUCTION_MOVE	CONSTANT NUMBER := 362;   -- Pallet belongs to Mini Load
	QTY_NOT_IN_CASES	CONSTANT NUMBER := 363;   -- Adjusted Quantity must be in Cases
	INVALID_DATE		CONSTANT NUMBER := 364;   -- generated due to date conversion error in Oracle
	NO_CHANGE		CONSTANT NUMBER := 1001;  -- No change between old status and adjusted status
	MANIFEST_CLOSE		CONSTANT NUMBER := 1002;  -- Manifest must be closed for confirm putaway
	SYS_CUST_WARN		CONSTANT NUMBER := 1003;  -- Warning to user that item is past cust + sysco shelf life
	MFR_SHELF_WARN		CONSTANT NUMBER := 1004;  -- Warning to user that item is past mfg shelf life
	PAST_SHELF_WARN		CONSTANT NUMBER := 1005;  -- Warning to user that item is past cust + sysco or mfg shelf life
	EXP_WARN		CONSTANT NUMBER := 1006;  -- Warning to user that item will appear on expiration date warning report
	ER_SEND_FAILED		CONSTANT NUMBER := 1007;  -- Expected Receipt Message Failed
	INVALID_ML_ITEM		CONSTANT NUMBER := 1008;  -- Not a miniload item
	INVALID_IND_LOC		CONSTANT NUMBER := 1009;  -- Invalid Induction location
END pl_swms_error_codes;
/
-- CREATE OR REPLACE PUBLIC SYNONYM pl_swms_error_codes FOR swms.pl_swms_error_codes 
-- /
-- GRANT EXECUTE ON swms.pl_swms_error_codes TO swms_user
-- /
