/****************************************************************************
** Date:       05-MAY-2014
** File:       6000000054_European_Imports_DCL.sql
**
** Grants access to the tables created as part of 
**		European Imports integration
**
** Grants access to users SWMS_USER, SWMS_VIEWER & SWMS_JDBC on below tables
** 		1.CROSS_DOCK_DATA_COLLECT_IN
** 		2.CROSS_DOCK_DATA_COLLECT
** 		3.CROSS_DOCK_XREF
** 		4.CROSS_DOCK_STATUS
** 		5.CROSS_DOCK_TYPE
**		6.CROSS_DOCK_PALLET_XREF
**
** Modification History:
**    Date     Designer Comments
**    -------- -------- ---------------------------------------------------
**    05-MAY-14 Infosys  Granted access to EI tables
**
****************************************************************************/

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_DATA_COLLECT_IN TO SWMS_USER;
GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_DATA_COLLECT_IN TO SWMS_JDBC;
GRANT SELECT ON SWMS.CROSS_DOCK_DATA_COLLECT_IN TO SWMS_VIEWER;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SWMS.CROSS_DOCK_DATA_COLLECT_IN TO SWMS_SAP;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_DATA_COLLECT TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_DATA_COLLECT TO SWMS_VIEWER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_XREF TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_XREF TO SWMS_VIEWER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_STATUS TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_STATUS TO SWMS_VIEWER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_TYPE TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_TYPE TO SWMS_VIEWER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_PALLET_XREF TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_PALLET_XREF TO SWMS_VIEWER;

GRANT EXECUTE ON SWMS.PL_RCV_CROSS_DOCK TO SWMS_USER;
GRANT EXECUTE ON SWMS.PL_RCV_CROSS_DOCK TO SWMS_VIEWER;
GRANT EXECUTE ON SWMS.PL_RCV_CROSS_DOCK TO SWMS_SAP;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.CROSS_DOCK_STATUS TO SWMS_USER;
GRANT SELECT ON SWMS.CROSS_DOCK_STATUS TO SWMS_VIEWER;

GRANT ALTER, SELECT ON SWMS.CROSS_DOCK_DATA_COLLECT_SEQ TO SWMS_JDBC;
GRANT ALTER, SELECT ON SWMS.CROSS_DOCK_DATA_COLLECT_SEQ TO SWMS_SAP;
GRANT SELECT ON SWMS.CROSS_DOCK_DATA_COLLECT_SEQ TO SWMS_USER;