/*****************************************************************************
**    Insert records for SWMS_ALERT_NOTIFICATION  FOR charm No: 6000008477
******************************************************************************/

Insert into SWMS_ALERT_NOTIFICATION
   (MODULES, ERROR_TYPE, CREATE_TICKET, SEND_EMAIL, PRIMARY_RECIPIENT, ALTERNATE_RECIPIENT)
Values
   ('MINILOAD_EXCEPTION', 'CRIT', 'N', 'Y', NULL, NULL);
Insert into SWMS_ALERT_NOTIFICATION
   (MODULES, ERROR_TYPE, CREATE_TICKET, SEND_EMAIL, PRIMARY_RECIPIENT, ALTERNATE_RECIPIENT)
Values
   ('PL_AUTO_ROUTE_CLOSE', 'CRIT', 'N', 'Y', NULL, NULL);
Insert into SWMS_ALERT_NOTIFICATION
   (MODULES, ERROR_TYPE, CREATE_TICKET, SEND_EMAIL, PRIMARY_RECIPIENT, ALTERNATE_RECIPIENT)
Values
   ('COLLECTDATA', 'CRIT', 'N', 'Y', NULL, NULL);
Insert into SWMS_ALERT_NOTIFICATION
   (MODULES, ERROR_TYPE, CREATE_TICKET, SEND_EMAIL, PRIMARY_RECIPIENT, ALTERNATE_RECIPIENT)
Values
   ('PAECW', 'CRIT', 'N', 'Y', NULL, NULL);
COMMIT;


