
/***  Creation OF Audit Table for SWMS Utility transactions  ***/
CREATE TABLE SWMS.UTILITY_AUDIT
(
  TASK    VARCHAR2(80 CHAR)                 NOT NULL,
  USER_ID    VARCHAR2(15 CHAR)                 NOT NULL,
  ADD_DATE    DATE
);


CREATE OR REPLACE PUBLIC SYNONYM UTILITY_AUDIT FOR SWMS.UTILITY_AUDIT;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.UTILITY_AUDIT TO SWMS_USER;

GRANT SELECT ON SWMS.UTILITY_AUDIT TO SWMS_VIEWER;

