Insert into SWMS.GLOBAL_REPORT_DICT
   (LANG_ID, REPORT_NAME, FLD_LBL_NAME, FLD_LBL_DESC, MAX_LEN)
 Values
   (3, 'rp2ra', 'AREA', 'Area', 1);
Insert into SWMS.GLOBAL_REPORT_DICT
   (LANG_ID, REPORT_NAME, FLD_LBL_NAME, FLD_LBL_DESC, MAX_LEN)
 Values
   (12, 'rp2ra', 'AREA', 'Region', 1);
COMMIT;