   DELETE FROM SWMS.MESSAGE_TABLE WHERE ID_MESSAGE in ('13381','13383','13384','13385','13341');
   INSERT INTO SWMS.MESSAGE_TABLE(ID_MESSAGE,V_MESSAGE,ID_LANGUAGE) VALUES('13381' , 'Enable Queue - %s1 Returned - %s2' , '3');
   INSERT INTO SWMS.MESSAGE_TABLE(ID_MESSAGE,V_MESSAGE,ID_LANGUAGE) VALUES('13383' , 'Disable Queue - %s1 Returned - %s2' , '3');
   INSERT INTO SWMS.MESSAGE_TABLE(ID_MESSAGE,V_MESSAGE,ID_LANGUAGE) VALUES('13384' , 'Clear Queue - %s1 Returned - %s2' , '3');
   INSERT INTO SWMS.MESSAGE_TABLE(ID_MESSAGE,V_MESSAGE,ID_LANGUAGE) VALUES('13385' , 'Format Barcodes - %s1 Returned - %s2' , '3');
   INSERT INTO SWMS.MESSAGE_TABLE(ID_MESSAGE,V_MESSAGE,ID_LANGUAGE) VALUES('13341' , 'The Printer qDaemon has been Restarted !!','3');
   commit;
/  
