DELETE FROM swms.SYS_CONFIG WHERE CONFIG_FLAG_NAME = 'LXLI_DOMAIN';

INSERT INTO swms.SYS_CONFIG(SEQ_NO,APPLICATION_FUNC,CONFIG_FLAG_NAME,CONFIG_FLAG_DESC,
                CONFIG_FLAG_VAL,VALUE_REQUIRED,VALUE_UPDATEABLE,VALUE_IS_BOOLEAN,
                DATA_TYPE,DATA_PRECISION,DATA_SCALE,SYS_CONFIG_LIST)
VALUES ((SELECT MAX(SEQ_NO) + 1 FROM SWMS.SYS_CONFIG) ,'LABOR MGMT','LXLI_DOMAIN','LXLI server Domain','.na.sysco.net',
          'Y','N','N','CHAR','20','0','L');

INSERT INTO SWMS.SYS_CONFIG_VALID_VALUES values ('LXLI_DOMAIN','.na.sysco.net','LXLI flex server Domain');
INSERT INTO SWMS.SYS_CONFIG_VALID_VALUES values ('LXLI_DOMAIN',' ','LXLI flex server Domain');

commit;
