INSERT INTO SYS_CONFIG (SEQ_NO, APPLICATION_FUNC, CONFIG_FLAG_NAME, CONFIG_FLAG_DESC,
                        CONFIG_FLAG_VAL, VALUE_REQUIRED, VALUE_UPDATEABLE,
                        VALUE_IS_BOOLEAN, DATA_TYPE, DATA_PRECISION, SYS_CONFIG_LIST,
                        SYS_CONFIG_HELP, VALIDATION_TYPE)
VALUES ((SELECT MAX(SEQ_NO+1) FROM SYS_CONFIG), 'GENERAL', 'ACCEPT_EITHER_UPC',
        'SCAN INT OR EXT UPC AT PICK',
        'Y', 'Y', 'N', 'N', 'CHAR', 1, 'N',
        'ALLOWS SELECTOR TO SCAN EITHER THE INTERNAL OR EXTERNAL UPC TO VERIFY SELECTION',
        'LIST');
INSERT INTO SYS_CONFIG_VALID_VALUES (CONFIG_FLAG_NAME, CONFIG_FLAG_VAL, DESCRIPTION)
VALUES ('ACCEPT_EITHER_UPC','N',
        'SCAN INTERNAL UPC TO VERIFY SPLIT AND EXTERNAL_UPC TO VERIFY CASE SELECTION');
INSERT INTO SYS_CONFIG_VALID_VALUES (CONFIG_FLAG_NAME, CONFIG_FLAG_VAL, DESCRIPTION)
VALUES ('ACCEPT_EITHER_UPC','Y',
        'ALLOW SELECTOR TO SCAN EITHER THE INTERNAL OR EXTERNAL UPC TO VERIFY SELECTION');
COMMIT;

