---pdas8114 add MATRIX_DRY_CHEMICAL value to sys_config CRQ7742
DECLARE
V_SEQ NUMBER;
BEGIN
SELECT MAX(SEQ_NO)+1 INTO V_SEQ
FROM SYS_CONFIG;
Insert into SWMS.SYS_CONFIG
   (SEQ_NO, APPLICATION_FUNC, CONFIG_FLAG_NAME, CONFIG_FLAG_DESC, CONFIG_FLAG_VAL, 
    VALUE_REQUIRED, VALUE_UPDATEABLE, VALUE_IS_BOOLEAN, DATA_TYPE, DATA_PRECISION, 
    DATA_SCALE, SYS_CONFIG_LIST, VALIDATION_TYPE)
 Values
   (V_SEQ,'ORDER PROCESSING', 'MATRIX_DRY_CHEMICAL', 'Matrix Dry Chemical', 'DSLCHM', 
    'N', 'Y', 'N', 'CHAR', 10, 
    0, 'T', 'NONE');
END;
/
