INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_STAGING_HDR_OUT', 90, 'LXLI Staging header records',SYSDATE, USER);

INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_STAGING_SL_OUT', 90, 'LXLI Staging Selector records',SYSDATE, USER); 

INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_STAGING_LD_OUT', 90, 'LXLI Staging Loader records',SYSDATE, USER); 

INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_STAGING_FL_HEADER_OUT', 90, 'LXLI Staging FK header records',SYSDATE, USER); 

INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_STAGING_FL_INV_OUT', 90, 'LXLI Staging FK inventory records',SYSDATE, USER); 

INSERT INTO SWMS.SAP_INTERFACE_PURGE (
  TABLE_NAME,RETENTION_DAYS, DESCRIPTION,UPD_DATE, UPD_USER) 
VALUES ( 'LXLI_GOALTIME_IN', 90, 'LXLI Staging goal time records',SYSDATE, USER); 
