start /swms/curr/schemas/DDL_create_sts_routein_xml_in_seq.sql
start /swms/curr/schemas/DDL_create_sts_route_xml_in_tab.sql
start /swms/curr/schemas/DDL_create_sts_routein_at_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_ca_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_cw_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_di_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_ip_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_iv_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_ot_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_rj_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_rt_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_sp_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_sr_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_st_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_tf_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_ti_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_et_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_driverproresponse_obj.sql
start /swms/curr/schemas/DDL_create_sts_routein_xml_tab2_tab.sql
start /swms/curr/schemas/DML_create_sts_routin_alert_notif.sql
start /swms/curr/schemas/DML_create_sts_routein_syspar.sql
start /swms/curr/schemas/pl_xml_sts_route_in.sql