--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
REM INSERTING into SWMS.GLOBAL_DATE_FORMAT
SET DEFINE OFF;
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (1,'mm/dd/yy');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (2,'mm/dd/yyyy');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (3,'dd-mon-yy');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (4,'%m/%d/%y');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (5,'mm/dd/yy HH24:MI');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (6,'MM/DD/YY HH24:MI:SS');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (7,'mm/dd/yyyy HH24:mi:SS');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (8,'DD-MON-YY HH24:MI');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (9,'DD-MON-YY HH24:MI:SS');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (12,'mmddyy');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (18,'DD-MON-YY');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (13,'MM-DD');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (19,'MM/DD/YY HH12AM');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (11,'MMDDYYYY');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (16,'MM/DD HH24:MI:SS');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (15,'HH24:MI');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (14,'MM/DD HH24:MI');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (17,'MM/DD/YY');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (10,'HH24:MI:SS');
Insert into SWMS.GLOBAL_DATE_FORMAT (FORMAT_SEQ,FORMAT_MASK) values (20,'MM/DD/RR HH24:MI');
COMMIT;