/******************************************************************
*  JIRA 3125 Add RTN column to default job code screen  
*   
*
******************************************************************/ 

DECLARE
v_row_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO  v_row_count
    FROM  swms.job_code
    WHERE substr(jbcd_job_code,4,3) = 'RTN';
	IF v_row_count = 0 THEN
      
		Insert into JOB_CODE (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) values ('FZRRTN','FF','DC','F','Y',1,'RETURN FROZEN','Y',1000,null,null,null,682,null,null,null,null,null,null,166,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
		Insert into JOB_CODE (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) values ('DRYRTN','DF','DC','D','Y',1,'RETURN DRY','Y',1000,null,null,null,510,null,null,null,null,null,null,164,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
		Insert into JOB_CODE (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) values ('CLRRTN','CF','DC','C','Y',1,'RETURN COOL','Y',1000,null,null,null,675,null,null,null,null,null,null,161,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
	commit;
	END IF;
END;
/