DECLARE
    row_cnt PLS_INTEGER := 0;
BEGIN
    SELECT COUNT(*)
    INTO  row_cnt
    FROM  swms.job_code
    WHERE SUBSTR(jbcd_job_code, 4, 3) = 'SWP';

    IF row_cnt = 0 THEN

        INSERT INTO swms.job_code (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) 
        VALUES ('FZRSWP','FF','FL','F','Y',1,'FREEZER SWAP','Y',1000,null,null,null,682,null,null,null,null,null,null,166,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

        INSERT INTO swms.job_code (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) 
        VALUES ('DRYSWP','DF','FL','D','Y',1,'DRY SWAP','Y',1000,null,null,null,510,null,null,null,null,null,null,164,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

        INSERT INTO swms.job_code (JBCD_JOB_CODE,JBCL_JOB_CLASS,LFUN_LBR_FUNC,WHAR_AREA,ENGR_STD_FLAG,MASK_LVL,DESCRIP,CORP_CODE,TMU_DOC_TIME,TMU_CUBE,TMU_WT,TMU_NO_PIECE,TMU_NO_PALLET,TMU_NO_ITEM,TMU_NO_DATA_CAPTURE,TMU_NO_PO,TMU_NO_STOP,TMU_NO_ZONE,TMU_NO_LOC,TMU_NO_CASE,TMU_NO_SPLIT,TMU_NO_MERGE,TMU_NO_AISLE,TMU_NO_DROP,TMU_ORDER_TIME,EXP_PERF,TMU_NO_CART,TMU_NO_PALLET_PIECE,TMU_NO_CART_PIECE,SN_RCV_JBCD,TMU_NO_SHORT,TMU_NO_CLAM_BED_DATA_CAPTURE,TMU_WALK,TMU_WALK_EQUIPMENT,EXCLUDE_GOAL_CALC) 
        VALUES ('CLRSWP','CF','FL','C','Y',1,'COOLER SWAP','Y',1000,null,null,null,675,null,null,null,null,null,null,161,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

        COMMIT;

    END IF;
END;
/
