ALTER TABLE SYNTELIC_LOADMAPPING_IN MODIFY(ROUTE_NO VARCHAR(10) NOT NULL);
ALTER TABLE SYNTELIC_LOADMAPPING_IN MODIFY(TRUCK_NO VARCHAR(10) NOT NULL);
ALTER TABLE SYNTELIC_LOADMAPPING_IN MODIFY(FLOAT_SEQUENCE VARCHAR(3) NOT NULL); 
