--  06-Jul-2012 - Add index to SWMS inbound interface staging tables 
--		to improve performance.

/****************************************************************************
** Date:       06-JUL-2011
** File:       CRQ33783_SAP_INDEX_ddl.sql
**
** Create indexes for staging tables to improve performance
**
**
** Modification History:
**    Date     Designer Comments
**    -------- -------- ---------------------------------------------------
**    07/06/12 ssin2436 CRQ33783
**                      Project: Modify SWMS inbound interfaces to improve
**                      performance. Added index for SAP staging tables
**
**
****************************************************************************/

CREATE INDEX SWMS.SAP_IM_IN_IDX2
ON SWMS.SAP_IM_IN (PROD_ID);


CREATE INDEX SWMS.SAP_PO_IN_IDX2
ON SWMS.SAP_PO_IN (ERM_ID);


CREATE INDEX SWMS.SAP_MF_IN_IDX2
ON SWMS.SAP_MF_IN (MANIFEST_NO);


CREATE INDEX SWMS.SAP_SN_IN_IDX2
ON SWMS.SAP_SN_IN (SN_NO);


CREATE INDEX SWMS.SAP_CONTAINER_OUT_IDX1 ON SWMS.SAP_CONTAINER_OUT (RECORD_STATUS); 

CREATE INDEX SWMS.SAP_CR_OUT_IDX1
ON SWMS.SAP_CR_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_CS_IN_IDX1
ON SWMS.SAP_CS_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_CU_IN_IDX1
ON SWMS.SAP_CU_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_EQUIP_OUT_IDX1
ON SWMS.SAP_EQUIP_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_IA_OUT_IDX1
ON SWMS.SAP_IA_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_IM_IN_IDX1
ON SWMS.SAP_IM_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_MF_IN_IDX1
ON SWMS.SAP_MF_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_ML_IN_IDX1
ON SWMS.SAP_ML_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_OR_IN_IDX1
ON SWMS.SAP_OR_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_OW_OUT_IDX1
ON SWMS.SAP_OW_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_PO_IN_IDX1
ON SWMS.SAP_PO_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_RT_OUT_IDX1
ON SWMS.SAP_RT_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_SN_IN_IDX1
ON SWMS.SAP_SN_IN (RECORD_STATUS);


CREATE INDEX SWMS.SAP_WH_OUT_IDX1
ON SWMS.SAP_WH_OUT (RECORD_STATUS);


CREATE INDEX SWMS.SAP_LM_OUT_IDX1
ON SWMS.SAP_LM_OUT (RECORD_STATUS);


CREATE INDEX SWMS.CUBITRON_ITEMMASTER_OUT_IDX1 ON SWMS.CUBITRON_ITEMMASTER_OUT (RECORD_STATUS); 

CREATE INDEX SWMS.CUBITRON_MEASUREMENT_IN_IDX1 ON SWMS.CUBITRON_MEASUREMENT_IN (RECORD_STATUS); 

CREATE INDEX SWMS.SYNTELIC_LOADMAPPING_IN_IDX1 ON SWMS.SYNTELIC_LOADMAPPING_IN (RECORD_STATUS); 

CREATE INDEX SWMS.SYNTELIC_MATERIAL_OUT_IDX1 ON SWMS.SYNTELIC_MATERIAL_OUT (RECORD_STATUS); 

CREATE INDEX SWMS.SYNTELIC_ROUTE_ORDER_OUT_IDX1
ON SWMS.SYNTELIC_ROUTE_ORDER_OUT (RECORD_STATUS); 

