CREATE TABLE SWMS.DOD_LABEL_HEADER
(
  ROUTE_NO           VARCHAR2(10 CHAR)     NOT NULL,
  ORDER_ID           VARCHAR2(14 CHAR)     NOT NULL,
  STOP_NO            NUMBER(7,2)           NOT NULL,
  TRUCK_NO           VARCHAR2(10 CHAR),
  SHIP_DATE          DATE,
  STATUS             VARCHAR2(3 CHAR)      NOT NULL,
  CUST_ID            VARCHAR2(10 CHAR)     NOT NULL,
  CUST_NAME          VARCHAR2(30 CHAR),
  DOD_CONTRACT_NO    VARCHAR2(13 CHAR)     NOT NULL,
  ADD_DATE           DATE,
  ADD_USER           VARCHAR2(30 CHAR),
  PRINT_USER         VARCHAR2(30 CHAR),
  PRINT_FLAG         VARCHAR2(1 CHAR)      DEFAULT 'N',
  PRINT_DATE         DATE
);

CREATE INDEX SWMS.DOD_LABEL_HEADER_IDX1 ON SWMS.DOD_LABEL_HEADER(ROUTE_NO);

CREATE UNIQUE INDEX SWMS.DOD_LABEL_HEADER_IDX2 ON SWMS.DOD_LABEL_HEADER(ORDER_ID);

CREATE OR REPLACE PUBLIC SYNONYM DOD_LABEL_HEADER FOR SWMS.DOD_LABEL_HEADER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.DOD_LABEL_HEADER TO SWMS_USER;

GRANT SELECT ON SWMS.DOD_LABEL_HEADER TO SWMS_VIEWER;

CREATE TABLE SWMS.DOD_LABEL_DETAIL
(
  ORDER_ID               VARCHAR2(14 CHAR)      NOT NULL,
  ORDER_LINE_ID          NUMBER(3)              NOT NULL,
  PROD_ID                VARCHAR2(9 CHAR)       NOT NULL,
  ROUTE_NO               VARCHAR2(10 CHAR)      NOT NULL,
  SRC_LOC                VARCHAR2(10 CHAR),
  QTY_ALLOC              NUMBER(9),
  PALLET_ID              VARCHAR2(18 CHAR),
  BATCH_NO               NUMBER(9),
  MAX_CASE_SEQ           NUMBER(9),
  START_SEQ              NUMBER(9),
  END_SEQ                NUMBER(9),
  PACK_DATE              DATE,
  EXP_DATE               DATE,
  LOT_ID                 VARCHAR2(30 CHAR),
  DOD_CUST_ITEM_BARCODE  VARCHAR2(13 CHAR),
  DOD_FIC                VARCHAR2(3 CHAR),
  ADD_DATE               DATE,
  ADD_USER               VARCHAR2(30 CHAR),
  UPD_DATE               DATE,
  UPD_USER               VARCHAR2(30 CHAR)
 );

CREATE INDEX SWMS.DOD_LABEL_DETAIL_IDX ON SWMS.DOD_LABEL_DETAIL(ROUTE_NO);

CREATE INDEX SWMS.DOD_LABEL_DETAIL_IDX1 ON SWMS.DOD_LABEL_DETAIL(ORDER_ID,ORDER_LINE_ID);

CREATE INDEX SWMS.DOD_LABEL_DETAIL_IDX2 ON SWMS.DOD_LABEL_DETAIL(PROD_ID);

CREATE INDEX SWMS.DOD_LABEL_DETAIL_IDX3 ON SWMS.DOD_LABEL_DETAIL(SRC_LOC);

CREATE OR REPLACE PUBLIC SYNONYM DOD_LABEL_DETAIL FOR SWMS.DOD_LABEL_DETAIL;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.DOD_LABEL_DETAIL TO SWMS_USER;

GRANT SELECT ON SWMS.DOD_LABEL_DETAIL TO SWMS_VIEWER;

ALTER TABLE ORDM ADD (DOD_CONTRACT_NO VARCHAR2(13 CHAR));

ALTER TABLE ORDD ADD (DOD_CUST_ITEM_BARCODE VARCHAR2(13 CHAR), DOD_FIC VARCHAR2(3 CHAR));
