/****************************************************************************
** Date:       23-OCT-2014
** File:       6000003789_Ireland_cubic_centimeter_ddl.sql
**
** Script to MODIFY table fields for Ireland Cubic value metric conversion.
**
** Modification History:
**    Date     Designer Comments
**    -------- -------- ---------------------------------------------------
**    10/23/14 Infosys  Modified the below table fields for Ireland metric conversion
**
****************************************************************************/
ALTER TABLE ARCH_BATCH MODIFY KVI_CUBE NUMBER(12,4);
ALTER TABLE ARCH_BATCH_HIST MODIFY KVI_CUBE NUMBER(12,4);
ALTER TABLE BATCH MODIFY KVI_CUBE NUMBER(12,4);
ALTER TABLE CASE_TYPE_CODE MODIFY MIN_CUBE NUMBER(12,4);
ALTER TABLE CASE_TYPE_CODE MODIFY MAX_CUBE NUMBER(12,4);
ALTER TABLE CUBITRON_ITEMMASTER_OUT MODIFY CASE_CUBE VARCHAR2(13);
ALTER TABLE CUBITRON_MEASUREMENT_IN MODIFY CASE_CUBE VARCHAR2(13);
ALTER TABLE CUBITRON_MEASUREMENT_IN_BK MODIFY CASE_CUBE VARCHAR2(13);
ALTER TABLE DFLT_LEVEL_HEIGHTS MODIFY LOC_CUBE NUMBER(12,4);
ALTER TABLE DS_PICKUP_OBJECT MODIFY CUBE NUMBER(12,4);
ALTER TABLE FLOAT_DETAIL MODIFY CUBE NUMBER(12,4);
ALTER TABLE FLOAT_DETAIL_BCKUP MODIFY CUBE NUMBER(12,4);
ALTER TABLE FLOATS MODIFY FLOAT_CUBE NUMBER(12,4);
ALTER TABLE FLOATS_BCKUP MODIFY FLOAT_CUBE NUMBER(12,4);
ALTER TABLE INV MODIFY CUBE NUMBER(12,4);
ALTER TABLE INV_HIST MODIFY CUBE NUMBER(12,4);
ALTER TABLE INV_TMP MODIFY CUBE NUMBER(12,4);
ALTER TABLE JOB_CODE MODIFY TMU_CUBE NUMBER(12,4);
ALTER TABLE LAS_TRUCK MODIFY DRY_CUBE VARCHAR2(13);
ALTER TABLE LAS_TRUCK MODIFY COOLER_CUBE VARCHAR2(13);
ALTER TABLE LAS_TRUCK MODIFY FREEZER_CUBE VARCHAR2(13);
ALTER TABLE LAS_TRUCK_BCKUP MODIFY DRY_CUBE VARCHAR2(13);
ALTER TABLE LAS_TRUCK_BCKUP MODIFY COOLER_CUBE VARCHAR2(13);
ALTER TABLE LAS_TRUCK_BCKUP MODIFY FREEZER_CUBE VARCHAR2(13);
ALTER TABLE LM_ROUTE MODIFY TOTCUBE NUMBER(12,4);
ALTER TABLE LOC MODIFY CUBE NUMBER(12,4);
ALTER TABLE LOC MODIFY OLD_CUBE NUMBER(12,4);
ALTER TABLE MANIFEST_STOPS MODIFY INVOICE_CUBE NUMBER(12,4);
ALTER TABLE OB1RA_TMP MODIFY C_CUBE NUMBER(12,4);
ALTER TABLE OB1RA_TMP MODIFY D_CUBE NUMBER(12,4);
ALTER TABLE OB1RA_TMP MODIFY F_CUBE NUMBER(12,4);
ALTER TABLE PALLET_RET_CNTRL MODIFY PALLET_CUBE NUMBER(12,4);
ALTER TABLE PALLET_TYPE MODIFY CUBE NUMBER(12,4);
ALTER TABLE PALLET_TYPE MODIFY SKID_CUBE NUMBER(12,4);
ALTER TABLE PM MODIFY CASE_CUBE NUMBER(12,4);
ALTER TABLE PM MODIFY SPLIT_CUBE NUMBER(12,4);
ALTER TABLE PM_DIM_EXCEPTION MODIFY CASE_CUBE NUMBER(12,4);
ALTER TABLE PRE_LOC MODIFY CUBE NUMBER(12,4);
ALTER TABLE SAP_IM_IN MODIFY CASE_CUBE VARCHAR2(13);
ALTER TABLE SAP_MF_IN MODIFY INVOICE_CUBE VARCHAR2(13);
ALTER TABLE SEL_EQUIP MODIFY LOW_CUBE NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY HIGH_CUBE NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY MIN_CUBE_UNITIZE NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY PCT_FLOAT_OVERCUBE NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY REPALLET_CUBE_CLR NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY REPALLET_CUBE_DRY NUMBER(12,4);
ALTER TABLE SEL_EQUIP MODIFY REPALLET_CUBE_FRZ NUMBER(12,4);
ALTER TABLE SN_HEADER MODIFY SHIPPED_CUBE NUMBER(12,4);
ALTER TABLE SOS_BATCH MODIFY BATCH_CUBE NUMBER(12,4);
ALTER TABLE SOS_BATCH_BCKUP MODIFY BATCH_CUBE NUMBER(12,4);
ALTER TABLE SOS_BATCH_HIST MODIFY BATCH_CUBE NUMBER(12,4);
ALTER TABLE STS_ROUTE_INVOICE MODIFY INVOICE_CUBE VARCHAR2(13);
ALTER TABLE SYNTELIC_MATERIAL_OUT MODIFY CASE_CUBE VARCHAR2(13);
ALTER TABLE T_CURR_BATCH MODIFY FLOAT_CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH MODIFY CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH MODIFY CASE_CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH MODIFY SPLIT_CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH_SHORT MODIFY FLOAT_CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH_SHORT MODIFY CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH_SHORT MODIFY CASE_CUBE NUMBER(12,4);
ALTER TABLE T_CURR_BATCH_SHORT MODIFY SPLIT_CUBE NUMBER(12,4);
ALTER TABLE WHMV_MINILOAD_ITEM MODIFY CUBE NUMBER(12,4);
ALTER TABLE WHMVELOC MODIFY CUBE NUMBER(12,4);
ALTER TABLE WHMVELOC_ERROR MODIFY CUBE NUMBER(12,4);
ALTER TABLE WHMVELOC_ERROR_HIST MODIFY CUBE NUMBER(12,4);
ALTER TABLE WHMVELOC_HIST MODIFY CUBE NUMBER(12,4);

COMMIT;
