--CHARM#6000000676- Provide Alert when record in SAP Staging Failed
CREATE TABLE SWMS.SWMS_FAILURE_EVENT
(
  ALERT_ID     NUMBER,
  MODULES      VARCHAR2(20 CHAR),
  ERROR_TYPE   VARCHAR2(4 CHAR),
  UNIQUE_ID    VARCHAR2(48 CHAR)                NOT NULL,
  STATUS       VARCHAR2(1 CHAR)                     NOT NULL,
  MSG_SUBJECT  VARCHAR2(100 CHAR),
  MSG_BODY     VARCHAR2(400 CHAR)                   NOT NULL,
  ADD_DATE     DATE,
  ADD_USER     VARCHAR2(10 CHAR)
);

CREATE TABLE SWMS.SWMS_ALERT_NOTIFICATION
(
  MODULES               VARCHAR2(20 CHAR),
  ERROR_TYPE            VARCHAR2(4 CHAR),
  CREATE_TICKET         VARCHAR2(1 CHAR),
  SEND_EMAIL            VARCHAR2(1 CHAR),
  PRIMARY_RECIPIENT    VARCHAR2(250 CHAR),
  ALTERNATE_RECIPIENT  VARCHAR2(250 CHAR)
);


CREATE SEQUENCE swms.failure_seq
START WITH 1
MAXVALUE 9999999
MINVALUE 1
CYCLE
CACHE 20
ORDER;
 
CREATE OR REPLACE PUBLIC SYNONYM failure_seq FOR swms.failure_seq;

CREATE OR REPLACE PUBLIC SYNONYM SWMS_FAILURE_EVENT FOR SWMS.SWMS_FAILURE_EVENT;

CREATE OR REPLACE PUBLIC SYNONYM SWMS_ALERT_NOTIFICATION FOR SWMS.SWMS_ALERT_NOTIFICATION;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.SWMS_FAILURE_EVENT TO SWMS_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.SWMS_ALERT_NOTIFICATION TO SWMS_USER;

GRANT SELECT ON swms.failure_seq TO SWMS_USER;