/*** 6000011043  Correcting the Constraint name in GLOBAL_REPORT_DICT Table  ***/ 

ALTER TABLE SWMS.GLOBAL_REPORT_DICT RENAME CONSTRAINT " GLOBAL_REPORT_DICT_PK" TO "GLOBAL_REPORT_DICT_PK";

ALTER INDEX SWMS." GLOBAL_REPORT_DICT_PK" RENAME TO "GLOBAL_REPORT_DICT_PK";
