CREATE TABLE SWMS.ALERT_AUDIT
(
  MODULES                  VARCHAR2(20 CHAR),
  DESCRIP                  VARCHAR2(80 CHAR),
  UPD_USER                 VARCHAR2(15 CHAR)    DEFAULT REPLACE(USER, 'OPS$') NOT NULL,
  UPD_DATE                 DATE                 DEFAULT SYSDATE,
  OLD_PRIMARY_RECIPIENT    VARCHAR2(250 CHAR),
  OLD_ALTERNATE_RECIPIENT  VARCHAR2(250 CHAR)
);

CREATE OR REPLACE PUBLIC SYNONYM ALERT_AUDIT FOR SWMS.ALERT_AUDIT;
GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.ALERT_AUDIT TO SWMS_USER;
GRANT SELECT ON SWMS.ALERT_AUDIT TO SWMS_VIEWER;



