
-- FOR SCI087

DROP TYPE SWMS.SAP_EQUIP_OBJECT_TABLE;

CREATE OR REPLACE TYPE SWMS.SAP_EQUIP_OBJECT AS OBJECT
(
    batch_id number(8) ,
    equip_id VARCHAR2(10),
    inspection_date	DATE,	
    equip_name VARCHAR2(20),
    status VARCHAR2(2),
    add_user VARCHAR2(30) 
);
/

CREATE OR REPLACE TYPE SWMS.SAP_EQUIP_OBJECT_TABLE AS TABLE of SAP_EQUIP_OBJECT;
/

CREATE OR REPLACE PUBLIC SYNONYM SAP_EQUIP_OUT for SWMS.SAP_EQUIP_OUT;

CREATE OR REPLACE PUBLIC SYNONYM SAP_EQUIP_OBJECT_TABLE  for SWMS.SAP_EQUIP_OBJECT_TABLE; 

grant all on SAP_EQUIP_OBJECT_TABLE to SWMS_SAP;

grant all on  PL_SAP_INTERFACES to SWMS_SAP; 

COMMIT;
