ALTER TABLE "SWMS"."ORDCW" 
    ADD ("CW_FLOAT_NO" NUMBER(7), "CW_SCAN_METHOD" CHAR(1));

ALTER TABLE SWMS.ORDCW
    ADD (CONSTRAINT ORDCW_PK PRIMARY KEY(ORDER_ID,ORDER_LINE_ID,SEQ_NO));

ALTER TABLE "SWMS"."SEL_EQUIP" 
    ADD ("REPALLET_CUBE_CLR" NUMBER(4, 2), "REPALLET_CUBE_DRY" 
    NUMBER(4, 2), "REPALLET_CUBE_FRZ" NUMBER(4, 2));

ALTER TABLE "SWMS"."FLOATS"
    ADD ("CW_COLLECT_STATUS" CHAR(1), "CW_COLLECT_USER" VARCHAR2(30));

CREATE TABLE "SWMS"."BULK_SHORT"
    ("FLOAT_NO" NUMBER(7) NOT NULL,
     "ORDER_SEQ" NUMBER(8) NOT NULL,
     "QTY_SHORT" NUMBER(4) NOT NULL);

