CREATE TABLE "SWMS"."RF_CLIENT_VERSION" ("HOST" VARCHAR2(30 byte)
    NOT NULL, "DEVICE" VARCHAR2(20 byte) NOT NULL, "APPLICATION" 
    VARCHAR2(10 byte) NOT NULL, "CLIENT_VERSION" VARCHAR2(15 
    byte) NOT NULL, "UPD_DATE" DATE NOT NULL, "UPD_USER" 
    VARCHAR2(30 byte) NOT NULL, 
    CONSTRAINT "RF_CLIENT_VERSION_PK" PRIMARY KEY("HOST", 
    "DEVICE", "APPLICATION") 
    USING INDEX  
    TABLESPACE "SWMS_DTS2" 
    STORAGE ( INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
    TABLESPACE "SWMS_DTS2" PCTFREE 10 PCTUSED 0 INITRANS 1 
    MAXTRANS 255 
    STORAGE ( INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 
    MONITORING;

CREATE OR REPLACE PUBLIC SYNONYM RF_CLIENT_VERSION FOR SWMS.RF_CLIENT_VERSION;

GRANT SELECT, INSERT, UPDATE, DELETE ON RF_CLIENT_VERSION TO SWMS_USER;
GRANT SELECT ON RF_CLIENT_VERSION TO SWMS_VIEWER;
