/****************************************************************************
** Date:       06-JUN-2013
** File:       CRQ46129_dba_schema.sql
**
**             Scripts for creating the backup tables
**             for Order Processing and SOS/SLS tables.
**
**    - SCRIPTS
**
**    Modification History:
**    Date      Designer Comments
**    --------  -------- --------------------------------------------------- **    
**    06-JUN-13 ssin2436 CRQ46129
**                       Project: CRQ46129_dba_schema.sql 
**  		         Need to backup Order Processing/SOS/SLS tables 
**            		 before purging each day for multiple reasons.  
**    01-AUG-13 sray0453 Added BKUP_DATE to store the timestamp on which 
**			 data backup is taken.                     
**
****************************************************************************/
spool ck_CRQ46129_dba_schema.lis
CREATE TABLE SWMS.FLOATS_BCKUP
(
  BATCH_NO           NUMBER(9),
  BATCH_SEQ          NUMBER(2),
  FLOAT_NO           NUMBER(9)                  NOT NULL,
  FLOAT_SEQ          VARCHAR2(4 CHAR),
  ROUTE_NO           VARCHAR2(10 CHAR),
  B_STOP_NO          NUMBER(7,2),
  E_STOP_NO          NUMBER(7,2),
  FLOAT_CUBE         NUMBER(7,2),
  GROUP_NO           NUMBER(3),
  MERGE_GROUP_NO     NUMBER(3),
  MERGE_SEQ_NO       NUMBER(3),
  MERGE_LOC          VARCHAR2(10 CHAR),
  ZONE_ID            VARCHAR2(5 CHAR),
  EQUIP_ID           VARCHAR2(10 CHAR),
  COMP_CODE          VARCHAR2(1 CHAR),
  SPLIT_IND          VARCHAR2(1 CHAR),
  PALLET_PULL        VARCHAR2(1 CHAR),
  PALLET_ID          VARCHAR2(18 CHAR),
  HOME_SLOT          VARCHAR2(10 CHAR),
  DROP_QTY           NUMBER(9),
  DOOR_AREA          VARCHAR2(1 CHAR),
  SINGLE_STOP_FLAG   VARCHAR2(1 CHAR),
  STATUS             VARCHAR2(3 CHAR),
  SHIP_DATE          DATE,
  PARENT_PALLET_ID   VARCHAR2(18 CHAR),
  FL_METHOD_ID       VARCHAR2(10 CHAR),
  FL_SEL_TYPE        VARCHAR2(3 CHAR),
  FL_OPT_PULL        VARCHAR2(1 CHAR),
  TRUCK_NO           VARCHAR2(10 CHAR),
  DOOR_NO            NUMBER(3),
  CW_COLLECT_STATUS  CHAR(1 CHAR),
  CW_COLLECT_USER    VARCHAR2(30 CHAR),
  BKUP_DATE	     DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.ROUTE_BCKUP
(
  ROUTE_NO          VARCHAR2(10 CHAR)           NOT NULL,
  SEQ_NO            NUMBER(3),
  TRUCK_NO          VARCHAR2(10 CHAR),
  SEL_LOCK          VARCHAR2(1 CHAR),
  ROUTE_BATCH_NO    NUMBER(7),
  SCH_TIME          DATE,
  DL_TIME           DATE,
  F_DOOR            NUMBER(3),
  C_DOOR            NUMBER(3),
  D_DOOR            NUMBER(3),
  METHOD_ID         VARCHAR2(10 CHAR),
  STOPS             NUMBER(3),
  STATUS            VARCHAR2(3 CHAR)            NOT NULL,
  COMBINE_PALLET    VARCHAR2(1 CHAR),
  FREEZER_FOLD      NUMBER(3),
  COOLER_FOLD       NUMBER(3),
  DRY_FOLD          NUMBER(3),
  STS_STATUS        VARCHAR2(1 CHAR),
  ADD_ON_ROUTE_SEQ  NUMBER(3),
  OLD_TRUCK_NO      VARCHAR2(10 CHAR),
  BKUP_DATE	     DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

CREATE TABLE SWMS.ORDM_BCKUP
(
  ORDER_ID           VARCHAR2(14 CHAR)          NOT NULL,
  ROUTE_NO           VARCHAR2(10 CHAR)          NOT NULL,
  STOP_NO            NUMBER(7,2)                NOT NULL,
  TRUCK_NO           VARCHAR2(10 CHAR),
  TRAILER_NO         VARCHAR2(10 CHAR),
  PRIORITY           NUMBER(3),
  TRUCK_TYPE         VARCHAR2(3 CHAR),
  SHIP_DATE          DATE,
  STATUS             VARCHAR2(3 CHAR)           NOT NULL,
  CUST_ID            VARCHAR2(10 CHAR)          NOT NULL,
  CARR_ID            VARCHAR2(10 CHAR),
  WAVE_NUMBER        VARCHAR2(5 CHAR),
  ORDER_TYPE         VARCHAR2(3 CHAR),
  UNITIZE_IND        VARCHAR2(1 CHAR),
  CUST_PO            VARCHAR2(15 CHAR),
  CUST_NAME          VARCHAR2(30 CHAR),
  CUST_CONTACT       VARCHAR2(30 CHAR),
  CUST_ADDR1         VARCHAR2(40 CHAR),
  CUST_ADDR2         VARCHAR2(40 CHAR),
  CUST_ADDR3         VARCHAR2(40 CHAR),
  CUST_CITY          VARCHAR2(20 CHAR),
  CUST_STATE         VARCHAR2(2 CHAR),
  CUST_ZIP           VARCHAR2(10 CHAR),
  CUST_CNTRY         VARCHAR2(10 CHAR),
  SHIP_ID            VARCHAR2(30 CHAR),
  SHIP_NAME          VARCHAR2(30 CHAR),
  SHIP_ADDR1         VARCHAR2(80 CHAR),
  SHIP_ADDR2         VARCHAR2(40 CHAR),
  SHIP_ADDR3         VARCHAR2(160 CHAR),
  SHIP_CITY          VARCHAR2(20 CHAR),
  SHIP_STATE         VARCHAR2(2 CHAR),
  SHIP_ZIP           VARCHAR2(10 CHAR),
  SHIP_CNTRY         VARCHAR2(10 CHAR),
  SALES              VARCHAR2(2 CHAR),
  GRPM_ID            VARCHAR2(30 CHAR),
  GRPM_SEQ           NUMBER(7),
  DEL_TIME           DATE,
  D_PIECES           NUMBER(9),
  C_PIECES           NUMBER(9),
  F_PIECES           NUMBER(9),
  WEIGHT             NUMBER(9,3),
  SYS_ORDER_ID       NUMBER(10),
  SYS_ORDER_LINE_ID  NUMBER(5),
  IMMEDIATE_IND      VARCHAR2(1 CHAR),
  DELIVERY_METHOD    VARCHAR2(1 CHAR),
  DELETED            VARCHAR2(3 CHAR),
  FRZ_SPECIAL        VARCHAR2(1 CHAR),
  CLR_SPECIAL        VARCHAR2(1 CHAR),
  DRY_SPECIAL        VARCHAR2(1 CHAR),
  OLD_STOP_NO        NUMBER(7,2),
  BKUP_DATE	     DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.ORDD_BCKUP
(
  ORDER_ID           VARCHAR2(14 CHAR)          NOT NULL,
  ORDER_LINE_ID      NUMBER(3)                  NOT NULL,
  PROD_ID            VARCHAR2(9 CHAR)           NOT NULL,
  CUST_PREF_VENDOR   VARCHAR2(10 CHAR)          NOT NULL,
  LOT_ID             VARCHAR2(30 CHAR),
  STATUS             VARCHAR2(3 CHAR),
  QTY_ORDERED        NUMBER(7)                  NOT NULL,
  QTY_SHIPPED        NUMBER(7),
  UOM                NUMBER(2),
  WEIGHT             NUMBER(9,2),
  PARTIAL            VARCHAR2(1 CHAR),
  PAGE               VARCHAR2(4 CHAR),
  INCK_KEY           VARCHAR2(5 CHAR),
  SEQ                NUMBER(8),
  AREA               VARCHAR2(1 CHAR),
  ROUTE_NO           VARCHAR2(10 CHAR),
  STOP_NO            NUMBER(7,2),
  QTY_ALLOC          NUMBER(7),
  ZONE_ID            VARCHAR2(5 CHAR),
  PALLET_PULL        VARCHAR2(1 CHAR),
  SYS_ORDER_ID       NUMBER(10),
  SYS_ORDER_LINE_ID  NUMBER(5),
  WH_OUT_QTY         NUMBER(7),
  REASON_CD          VARCHAR2(3 CHAR),
  PK_ADJ_TYPE        VARCHAR2(3 CHAR),
  PK_ADJ_DT          DATE,
  USER_ID            VARCHAR2(30 CHAR),
  CW_TYPE            VARCHAR2(1 CHAR),
  QA_TICKET_IND      VARCHAR2(1 CHAR),
  DELETED            VARCHAR2(3 CHAR),
  PCL_FLAG           VARCHAR2(1 CHAR),
  PCL_ID             VARCHAR2(14 CHAR),
  ORIGINAL_UOM       NUMBER(2),
  BKUP_DATE	     DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.ORD_COOL_BCKUP
(
  ORDER_ID           VARCHAR2(14 CHAR),
  ORDER_LINE_ID      NUMBER(3),
  SEQ_NO             NUMBER(4),
  PROD_ID            VARCHAR2(9 CHAR),
  CUST_PREF_VENDOR   VARCHAR2(10 CHAR),
  COUNTRY_OF_ORIGIN  VARCHAR2(2 CHAR),
  WILD_FARM          VARCHAR2(1 CHAR),
  ADD_DATE           DATE                       DEFAULT sysdate,
  ADD_USER           VARCHAR2(30 CHAR)          DEFAULT substr(user,1,10),
  UPD_DATE           DATE                       DEFAULT sysdate,
  UPD_USER           VARCHAR2(30 CHAR),
  BKUP_DATE	     DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";



CREATE TABLE SWMS.ORDCB_BCKUP
(
  ORDER_ID          VARCHAR2(14 CHAR)           NOT NULL,
  ORDER_LINE_ID     NUMBER(3)                   NOT NULL,
  SEQ_NO            NUMBER(4),
  PROD_ID           VARCHAR2(9 CHAR),
  CUST_PREF_VENDOR  VARCHAR2(10 CHAR),
  CLAM_BED_NO       VARCHAR2(10 CHAR),
  HARVEST_DATE      DATE,
  ADD_DATE          DATE                        DEFAULT sysdate,
  ADD_USER          VARCHAR2(30 CHAR)           DEFAULT user,
  UPD_DATE          DATE,
  UPD_USER          VARCHAR2(30 CHAR),
  BKUP_DATE	    DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

CREATE TABLE SWMS.ORDCW_BCKUP
(
  ORDER_ID          VARCHAR2(14 CHAR)           NOT NULL,
  ORDER_LINE_ID     NUMBER(3)                   NOT NULL,
  SEQ_NO            NUMBER(4),
  PROD_ID           VARCHAR2(9 CHAR),
  CUST_PREF_VENDOR  VARCHAR2(10 CHAR),
  CATCH_WEIGHT      NUMBER(9,3),
  CW_TYPE           VARCHAR2(1 CHAR),
  UOM               NUMBER(1),
  ADD_DATE          DATE                        DEFAULT sysdate,
  ADD_USER          VARCHAR2(30 CHAR)           DEFAULT user,
  UPD_DATE          DATE,
  UPD_USER          VARCHAR2(30 CHAR),
  CW_FLOAT_NO       NUMBER(7),
  CW_SCAN_METHOD    CHAR(1 CHAR),
  BKUP_DATE	    DATE			DEFAULT sysdate 
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.ORDMC_BCKUP
(
  ORDER_ID     VARCHAR2(14 CHAR)                NOT NULL,
  CMT_LINE_ID  NUMBER(3),
  CMT          VARCHAR2(75 CHAR),
  BKUP_DATE    DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.ORDDC_BCKUP
(
  ORDER_ID       VARCHAR2(14 CHAR)              NOT NULL,
  ORDER_LINE_ID  NUMBER(3),
  CMT_LINE_ID    NUMBER(3),
  CMT            VARCHAR2(75 CHAR),
  BKUP_DATE	 DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.LABEL_MASTER_BCKUP
(
  SEQ          NUMBER(3),
  BATCH_NO     NUMBER(7),
  QUEUE        VARCHAR2(7 CHAR),
  PRINT_GROUP  NUMBER(7),
  PRINT_FLAG   VARCHAR2(1 CHAR),
  BKUP_DATE    DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

CREATE TABLE SWMS.LABEL_HEADER_BCKUP
(
  BATCH_NO    NUMBER(8),
  SHIP_DATE   DATE,
  LABEL_SEQ   NUMBER(8),
  LABEL_TYPE  NUMBER(2),
  FLD_TEXT    LONG,
  BKUP_DATE   DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

CREATE TABLE SWMS.FLOAT_DETAIL_BCKUP
(
  FLOAT_NO          NUMBER(9)                   NOT NULL,
  SEQ_NO            NUMBER(3)                   NOT NULL,
  ZONE              NUMBER(2)                   NOT NULL,
  STOP_NO           NUMBER(7,2)                 NOT NULL,
  PROD_ID           VARCHAR2(9 CHAR)            NOT NULL,
  SRC_LOC           VARCHAR2(10 CHAR),
  MULTI_HOME_SEQ    NUMBER(5),
  UOM               NUMBER(2),
  QTY_ORDER         NUMBER(9),
  QTY_ALLOC         NUMBER(9),
  MERGE_ALLOC_FLAG  VARCHAR2(1 CHAR),
  MERGE_LOC         VARCHAR2(10 CHAR),
  STATUS            VARCHAR2(3 CHAR)            NOT NULL,
  ORDER_ID          VARCHAR2(14 CHAR),
  ORDER_LINE_ID     NUMBER(3),
  CUBE              NUMBER(7,2),
  COPY_NO           NUMBER(3),
  MERGE_FLOAT_NO    NUMBER(9),
  MERGE_SEQ_NO      NUMBER(3),
  CUST_PREF_VENDOR  VARCHAR2(10 CHAR)           NOT NULL,
  CLAM_BED_TRK      VARCHAR2(1 CHAR),
  ROUTE_NO          VARCHAR2(10 CHAR),
  ROUTE_BATCH_NO    NUMBER,
  ALLOC_TIME        DATE,
  REC_ID            VARCHAR2(12 CHAR),
  MFG_DATE          DATE,
  EXP_DATE          DATE,
  LOT_ID            VARCHAR2(30 CHAR),
  CARRIER_ID        VARCHAR2(18 CHAR),
  ORDER_SEQ         NUMBER(8),
  SOS_STATUS        VARCHAR2(1 CHAR),
  COOL_TRK          VARCHAR2(1 CHAR),
  CATCH_WT_TRK      VARCHAR2(1 CHAR),
  ITEM_SEQ          NUMBER(3),
  QTY_SHORT         NUMBER(3)                   DEFAULT 0,
  ST_PIECE_SEQ      NUMBER(3),
  SELECTOR_ID       VARCHAR2(10 CHAR),
  BC_ST_PIECE_SEQ   NUMBER(3),
  SHORT_ITEM_SEQ    NUMBER(4),
  BKUP_DATE	    DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";



CREATE TABLE SWMS.LAS_TRUCK_BCKUP
(
  TRUCK                  VARCHAR2(4 CHAR)       NOT NULL,
  TRAILER                VARCHAR2(6 CHAR),
  TRAILER_TYPE           VARCHAR2(20 CHAR),
  DRY_STATUS             VARCHAR2(1 CHAR),
  COOLER_STATUS          VARCHAR2(1 CHAR),
  FREEZER_STATUS         VARCHAR2(1 CHAR),
  LOADER                 VARCHAR2(30 CHAR),
  START_TIME             VARCHAR2(5 CHAR),
  COMPLETE_TIME          VARCHAR2(5 CHAR),
  LAST_PALLET            VARCHAR2(3 CHAR),
  DRY_PALLETS            VARCHAR2(3 CHAR),
  DRY_CASES              VARCHAR2(5 CHAR),
  DRY_STOPS              VARCHAR2(3 CHAR),
  DRY_CUBE               VARCHAR2(6 CHAR),
  DRY_REMAINING          VARCHAR2(3 CHAR),
  DRY_STACKHEIGHT        VARCHAR2(4 CHAR),
  COOLER_PALLETS         VARCHAR2(3 CHAR),
  COOLER_CASES           VARCHAR2(5 CHAR),
  COOLER_STOPS           VARCHAR2(3 CHAR),
  COOLER_CUBE            VARCHAR2(6 CHAR),
  COOLER_REMAINING       VARCHAR2(3 CHAR),
  COOLER_STACKHEIGHT     VARCHAR2(4 CHAR),
  FREEZER_PALLETS        VARCHAR2(3 CHAR),
  FREEZER_CASES          VARCHAR2(5 CHAR),
  FREEZER_STOPS          VARCHAR2(3 CHAR),
  FREEZER_CUBE           VARCHAR2(6 CHAR),
  FREEZER_REMAINING      VARCHAR2(3 CHAR),
  FREEZER_STACKHEIGHT    VARCHAR2(4 CHAR),
  NOTE1                  VARCHAR2(65 CHAR),
  NOTE2                  VARCHAR2(65 CHAR),
  NOTE3                  VARCHAR2(65 CHAR),
  ROUTE_NO               VARCHAR2(10 CHAR),
  TRUCK_STATUS           VARCHAR2(1 CHAR)       DEFAULT 'N',
  DRY_COMPLETE_TIME      DATE,
  DRY_COMPLETE_USER      VARCHAR2(30 CHAR),
  COOLER_COMPLETE_TIME   DATE,
  COOLER_COMPLETE_USER   VARCHAR2(30 CHAR),
  FREEZER_COMPLETE_TIME  DATE,
  FREEZER_COMPLETE_USER  VARCHAR2(30 CHAR),
  COMPLETE_USER          VARCHAR2(30 CHAR),
  BKUP_DATE	     	 DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.LAS_PALLET_BCKUP
(
  TRUCK             VARCHAR2(4 CHAR)            NOT NULL,
  PALLETNO          VARCHAR2(3 CHAR)            NOT NULL,
  TRUCK_ZONE        VARCHAR2(3 CHAR),
  LOADER_STATUS     VARCHAR2(1 CHAR),
  SELECTION_STATUS  VARCHAR2(1 CHAR),
  BATCH             VARCHAR2(7 CHAR),
  MAP_ZONE          VARCHAR2(3 CHAR),
  MAX_STOP          VARCHAR2(6 CHAR),
  MIN_STOP          VARCHAR2(6 CHAR),
  ADD_USER          VARCHAR2(30 CHAR)           DEFAULT REPLACE(USER,'OPS$',''),
  ADD_DATE          DATE                        DEFAULT SYSDATE,
  UPD_USER          VARCHAR2(30 CHAR),
  UPD_DATE          DATE,
  BKUP_DATE	    DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";



CREATE TABLE SWMS.SOS_SHORT_BCKUP
(
  AREA                   VARCHAR2(1 CHAR)       NOT NULL,
  ORDERSEQ               NUMBER(8)              NOT NULL,
  PICKTYPE               VARCHAR2(2 CHAR)       NOT NULL,
  BATCH_NO               VARCHAR2(7 CHAR),
  TRUCK                  VARCHAR2(4 CHAR),
  LOCATION               VARCHAR2(6 CHAR)       NOT NULL,
  DOCK_FLOAT_LOC         VARCHAR2(3 CHAR),
  QTY_TOTAL              NUMBER(3)              NOT NULL,
  QTY_SHORT              NUMBER(3)              NOT NULL,
  SOS_STATUS             VARCHAR2(1 CHAR),
  SHORT_TIME             DATE,
  FORK_STATUS            VARCHAR2(8 CHAR),
  RESOLUTION_TIME        DATE,
  SHORT_GROUP            VARCHAR2(1 CHAR),
  USER_ID                VARCHAR2(30 CHAR),
  SHORT_BATCH_NO         VARCHAR2(13 CHAR),
  SHORT_REASON           VARCHAR2(8 CHAR),
  PALLET                 VARCHAR2(4 CHAR),
  QTY_SHORT_ON_SHORT     NUMBER(3),
  SHORT_ON_SHORT_STATUS  VARCHAR2(1 CHAR),
  WHOUT_DATE             DATE,
  WHOUT_BY               VARCHAR2(30 CHAR),
  BKUP_DATE	     	 DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.SOS_BATCH_BCKUP
(
  BATCH_NO        VARCHAR2(14 CHAR)             NOT NULL,
  JOB_CODE        VARCHAR2(6 CHAR),
  BATCH_DATE      DATE                          NOT NULL,
  STATUS          CHAR(1 CHAR)                  NOT NULL,
  ROUTE_NO        VARCHAR2(10 CHAR),
  TRUCK_NO        VARCHAR2(10 CHAR),
  NO_OF_FLOATS    NUMBER(3),
  NO_OF_STOPS     NUMBER(3),
  NO_OF_CASES     NUMBER(4),
  NO_OF_SPLITS    NUMBER(4),
  NO_OF_MERGES    NUMBER(4),
  NO_OF_FDTLS     NUMBER(4),
  NO_OF_FDQTY     NUMBER(4),
  NO_OF_ITEMS     NUMBER(4),
  NO_OF_AISLES    NUMBER(3),
  NO_OF_ZONES     NUMBER(3),
  NO_OF_LOCNS     NUMBER(3),
  IS_UNITIZED     CHAR(1 CHAR),
  IS_OPTIMUM      CHAR(1 CHAR),
  PRT_BOX_CONTS   CHAR(1 CHAR),
  SHIP_DATE       DATE,
  BATCH_CUBE      NUMBER(7,3),
  PICKED_BY       VARCHAR2(10 CHAR),
  PICKED_TIME     DATE,
  RESERVED_BY     VARCHAR2(10 CHAR),
  REASSIGNED_BY   VARCHAR2(10 CHAR),
  LAST_PIK_LOC    VARCHAR2(10 CHAR),
  ORIG_BATCH_NO   VARCHAR2(14 CHAR),
  START_TIME      DATE,
  END_TIME        DATE,
  AREA            VARCHAR2(1 CHAR),
  RESERVED_TO     VARCHAR2(10 CHAR),
  POOLED_BY       VARCHAR2(10 CHAR),
  DOOR_NO         VARCHAR2(3 CHAR),
  ROUTE_BATCH_NO  NUMBER(7),
  ADD_DATE        DATE                          DEFAULT SYSDATE,
  ADD_USER        VARCHAR2(30 CHAR)             DEFAULT REPLACE(USER, 'OPS$'),
  UPD_DATE        DATE,
  UPD_USER        VARCHAR2(30 CHAR),
  BKUP_DATE	  DATE				DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.LAS_TRUCK_EQUIPMENT_BCKUP
(
  TRUCK          VARCHAR2(4 CHAR)               NOT NULL,
  COMPARTMENT    VARCHAR2(1 CHAR),
  TYPE_SEQ       NUMBER                         NOT NULL,
  LOADER_COUNT   NUMBER                         DEFAULT 0                     NOT NULL,
  INBOUND_COUNT  NUMBER                         DEFAULT 0,
  SHIP_DATE      DATE,
  BARCODE        VARCHAR2(14 CHAR),
  MANIFEST_NO    NUMBER(7),
  ROUTE_NO       VARCHAR2(10 CHAR),
  ADD_DATE       DATE                           DEFAULT SYSDATE,
  ADD_USER       VARCHAR2(30 CHAR)              DEFAULT REPLACE(USER, 'OPS$'),
  UPD_DATE       DATE,
  UPD_USER       VARCHAR2(30 CHAR),
  BKUP_DATE	 DATE				DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.LAS_TRUCK_SEAL_BCKUP
(
  TRUCK    VARCHAR2(4 CHAR)                     NOT NULL,
  SEAL_NO  VARCHAR2(10 CHAR)                    NOT NULL,
  BKUP_DATE	 DATE				DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

CREATE TABLE SWMS.LAS_CASE_BCKUP
(
  TRUCK      VARCHAR2(4 CHAR)                   NOT NULL,
  ORDER_SEQ  VARCHAR2(8 CHAR)                   NOT NULL,
  LABEL_SEQ  VARCHAR2(3 CHAR)                   NOT NULL,
  FLOAT_SEQ  VARCHAR2(4 CHAR),
  LOCATION   VARCHAR2(3 CHAR),
  BKUP_DATE  DATE				DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.SLS_USER_TRUCK_ACCESSORY_BCKUP
(
  ROUTE_NO          VARCHAR2(10 CHAR),
  TRUCK_NO          VARCHAR2(10 CHAR),
  COMPARTMENT       VARCHAR2(1 CHAR),
  TYPE_SEQ          NUMBER                      NOT NULL,
  LOADER_COUNT      NUMBER,
  INBOUND_COUNT     NUMBER,
  BARCODE           VARCHAR2(20 CHAR),
  SHIP_DATE         DATE,
  MANIFEST_NO       NUMBER(7),
  PALLET            VARCHAR2(4 CHAR),
  ADD_DATE          DATE                        DEFAULT SYSDATE,
  ADD_USER          VARCHAR2(30 CHAR)           DEFAULT REPLACE(USER,'OPS$',''),
  UPD_DATE          DATE,
  UPD_USER          VARCHAR2(30 CHAR),
  EDIT_TYPE         VARCHAR2(2 CHAR),
  EDIT_SEQ          NUMBER(7),
  OLD_LOADER_COUNT  NUMBER,
  BKUP_DATE         DATE			DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";


CREATE TABLE SWMS.SLS_LOAD_MAP_BCKUP
(
  ROUTE_NO     VARCHAR2(10 CHAR),
  TRUCK_NO     VARCHAR2(10 CHAR),
  LOAD_TYPE    VARCHAR2(1 CHAR),
  MAP_ZONE     NUMBER(2),
  ORIENTATION  VARCHAR2(1 CHAR),
  PALLET       VARCHAR2(4 CHAR),
  ADD_DATE     DATE                             DEFAULT SYSDATE,
  ADD_USER     VARCHAR2(30 CHAR)                DEFAULT REPLACE(USER,'OPS$',''),
  UPD_DATE     DATE,
  UPD_USER     VARCHAR2(30 CHAR),
  BKUP_DATE    DATE				DEFAULT sysdate
)
SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
 INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
 DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";



/***********************************************************************************************/
/* For granting permissions to the orders backup tables */
/***********************************************************************************************/

CREATE OR REPLACE PUBLIC SYNONYM FLOATS_BCKUP FOR SWMS.FLOATS_BCKUP;

GRANT ALL ON SWMS.FLOATS_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.FLOATS_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ROUTE_BCKUP FOR SWMS.ROUTE_BCKUP;

GRANT ALL ON SWMS.ROUTE_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ROUTE_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ORDM_BCKUP FOR SWMS.ORDM_BCKUP;


GRANT ALL ON SWMS.ORDM_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDM_BCKUP TO SWMS_VIEWER;




CREATE OR REPLACE PUBLIC SYNONYM ORDD_BCKUP FOR SWMS.ORDD_BCKUP;

GRANT ALL ON SWMS.ORDD_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDD_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ORD_COOL_BCKUP FOR SWMS.ORD_COOL_BCKUP;

GRANT ALL ON SWMS.ORD_COOL_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORD_COOL_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ORDCB_BCKUP FOR SWMS.ORDCB_BCKUP;

GRANT ALL ON SWMS.ORDCB_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDCB_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ORDCW_BCKUP FOR SWMS.ORDCW_BCKUP;

GRANT ALL ON SWMS.ORDCW_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDCW_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM ORDMC_BCKUP FOR SWMS.ORDMC_BCKUP;

GRANT ALL ON SWMS.ORDMC_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDMC_BCKUP TO SWMS_VIEWER;


CREATE OR REPLACE PUBLIC SYNONYM ORDDC_BCKUP FOR SWMS.ORDDC_BCKUP;

GRANT ALL ON SWMS.ORDDC_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.ORDDC_BCKUP TO SWMS_VIEWER;




CREATE OR REPLACE PUBLIC SYNONYM LABEL_MASTER_BCKUP FOR SWMS.LABEL_MASTER_BCKUP;

GRANT ALL ON SWMS.LABEL_MASTER_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LABEL_MASTER_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM LABEL_HEADER_BCKUP FOR SWMS.LABEL_HEADER_BCKUP;

GRANT ALL ON SWMS.LABEL_HEADER_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LABEL_HEADER_BCKUP TO SWMS_VIEWER;




CREATE OR REPLACE PUBLIC SYNONYM FLOAT_DETAIL_BCKUP FOR SWMS.FLOAT_DETAIL_BCKUP;

GRANT ALL ON SWMS.FLOAT_DETAIL_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.FLOAT_DETAIL_BCKUP TO SWMS_VIEWER;


CREATE OR REPLACE PUBLIC SYNONYM LAS_TRUCK_BCKUP FOR SWMS.LAS_TRUCK_BCKUP;

GRANT ALL ON SWMS.LAS_TRUCK_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LAS_TRUCK_BCKUP TO SWMS_VIEWER;




CREATE OR REPLACE PUBLIC SYNONYM LAS_PALLET_BCKUP FOR SWMS.LAS_PALLET_BCKUP;

GRANT ALL ON SWMS.LAS_PALLET_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LAS_PALLET_BCKUP TO SWMS_VIEWER;




CREATE OR REPLACE PUBLIC SYNONYM SOS_SHORT_BCKUP FOR SWMS.SOS_SHORT_BCKUP;

GRANT ALL ON SWMS.SOS_SHORT_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.SOS_SHORT_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM SOS_BATCH_BCKUP FOR SWMS.SOS_BATCH_BCKUP;

GRANT ALL ON SWMS.SOS_BATCH_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.SOS_BATCH_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM LAS_TRUCK_EQUIPMENT_BCKUP FOR SWMS.LAS_TRUCK_EQUIPMENT_BCKUP;

GRANT ALL ON SWMS.LAS_TRUCK_EQUIPMENT_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LAS_TRUCK_EQUIPMENT_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM LAS_TRUCK_SEAL_BCKUP FOR SWMS.LAS_TRUCK_SEAL_BCKUP;

GRANT ALL ON SWMS.LAS_TRUCK_SEAL_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LAS_TRUCK_SEAL_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM LAS_CASE_BCKUP FOR SWMS.LAS_CASE_BCKUP;

GRANT ALL ON SWMS.LAS_CASE_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.LAS_CASE_BCKUP TO SWMS_VIEWER;



CREATE OR REPLACE PUBLIC SYNONYM SLS_USER_TRUCK_ACCESSORY_BCKUP FOR SWMS.SLS_USER_TRUCK_ACCESSORY_BCKUP;

GRANT ALL ON SWMS.SLS_USER_TRUCK_ACCESSORY_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.SLS_USER_TRUCK_ACCESSORY_BCKUP TO SWMS_VIEWER;


CREATE OR REPLACE PUBLIC SYNONYM SLS_LOAD_MAP_BCKUP FOR SWMS.SLS_LOAD_MAP_BCKUP;

GRANT ALL ON SWMS.SLS_LOAD_MAP_BCKUP TO SWMS_USER;

GRANT SELECT ON SWMS.SLS_LOAD_MAP_BCKUP TO SWMS_VIEWER;
/
spool off
