CREATE TABLE SWMS.SOS_SHORT_DETAIL_BCKUP
  (
    BATCH_NO            VARCHAR2(7) NOT NULL,
    ORDERSEQ            NUMBER(8,0) NOT NULL,
    PICKTYPE            VARCHAR2(2) NOT NULL ,
    LOCATION            VARCHAR2(6) NOT NULL ,
    CASE_BARCODE        VARCHAR2(20) NOT NULL ,
    SHORT_REASON        VARCHAR2(8) NOT NULL ,
    FLOAT_NO            NUMBER(9,0),
    FLOAT_DETAIL_SEQ_NO NUMBER(3,0),
    PICK_LOCATION       VARCHAR2(6),
    PALLET_ID           VARCHAR2(18),
    BKUP_DATE           DATE DEFAULT SYSDATE
  )
   SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL  DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";
  
 
CREATE UNIQUE INDEX SWMS.XPKSOS_SHORT_DETAIL_BCKUP ON SWMS.SOS_SHORT_DETAIL_BCKUP
  (ORDERSEQ, LOCATION, PICKTYPE, CASE_BARCODE);
 
GRANT ALL ON SWMS.SOS_SHORT_DETAIL_BCKUP TO SWMS_USER;

CREATE OR REPLACE PUBLIC SYNONYM SOS_SHORT_DETAIL_BCKUP FOR swms.SOS_SHORT_DETAIL_BCKUP; 
 
 
 CREATE TABLE SWMS.MX_FLOAT_DETAIL_CASES_BCKUP
  (
    ORDER_SEQ               NUMBER(8,0) NOT NULL ,
    SEQ_NO                  NUMBER(4,0) NOT NULL ,
    CASE_ID                 NUMBER(13,0),
    BATCH_NO                NUMBER(9,0) NOT NULL ,
    ORDER_ID                VARCHAR2(14) NOT NULL ,
    ORDER_LINE_ID           NUMBER(3,0) NOT NULL ,
    UOM                     NUMBER(1,0) NOT NULL ,
    PROD_ID                 VARCHAR2(9) NOT NULL ,
    CUST_PREF_VENDOR        VARCHAR2(10) NOT NULL ,
    FLOAT_NO                NUMBER(9,0) NOT NULL ,
    FLOAT_DETAIL_SEQ_NO     NUMBER(9,0) NOT NULL ,
    FLOAT_DETAIL_ZONE       NUMBER(2,0) NOT NULL ,
    SWMS_PALLET_ID          VARCHAR2(18) NOT NULL ,
    MX_PALLET_ID            VARCHAR2(18),
    CASE_SHORT_FLAG         VARCHAR2(1) NOT NULL ,
    SHORT_REASON            VARCHAR2(8),
    CASE_RELEASE_TIMESTAMP  TIMESTAMP (6), 
    CASE_DIVERT_TIMESTAMP   TIMESTAMP (6),
    SPUR_LOCATION           VARCHAR2(10),
    LANE_ID                 NUMBER(2,0),
    SELECTOR_ID             VARCHAR2(30),
    SCAN_DATE               DATE,
    SCAN_TYPE               VARCHAR2(1),
    SCAN_METHOD             VARCHAR2(1),
    STATUS                  VARCHAR2(3) NOT NULL ,
    CASE_SKIP_FLAG          VARCHAR2(1),
    CASE_SKIP_REASON        VARCHAR2(10),
    SHORT_BATCH_NO          VARCHAR2(14),
    ADD_DATE                DATE NOT NULL ,
    ADD_USER                VARCHAR2(30) NOT NULL ,
    UPD_DATE                DATE,
    UPD_USER                VARCHAR2(30),
    BKUP_DATE               DATE DEFAULT SYSDATE    
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 3 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL  DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "SWMS_BACKUP";

 ;
 
CREATE UNIQUE INDEX SWMS.MX_FLOAT_DETAIL_CASES_BCKUP_UK ON SWMS.MX_FLOAT_DETAIL_CASES_BCKUP (CASE_ID);
   
CREATE UNIQUE INDEX SWMS.MX_FLOAT_DETAIL_CASES_BCKUP_PK ON SWMS.MX_FLOAT_DETAIL_CASES_BCKUP (ORDER_SEQ, SEQ_NO );
  
GRANT ALL ON SWMS.MX_FLOAT_DETAIL_CASES_BCKUP TO SWMS_USER;

CREATE OR REPLACE PUBLIC SYNONYM MX_FLOAT_DETAIL_CASES_BCKUP FOR swms.MX_FLOAT_DETAIL_CASES_BCKUP;   


  
  