DECLARE
  v_column_exists NUMBER := 0;  
BEGIN
  
  select count(*)
  into v_column_exists
  from all_objects
  where object_type = 'TYPE'
  and object_name = 'UPS_FLOAT_DTL_OBJ';

  IF (v_column_exists = 0)
  THEN
    EXECUTE IMMEDIATE 'create or replace TYPE  UPS_FLOAT_DTL_OBJ  AS OBJECT 
    (
	FLOAT_NO NUMBER(9),
	SEQ_NO NUMBER(3),
	PROD_ID VARCHAR2(9 CHAR),
	QTY_ALLOC NUMBER(9),
	UOM NUMBER(2),
	ORDER_SEQ NUMBER(8),
	ORDER_ID VARCHAR2(14 CHAR),
	ROUTE_NO VARCHAR2(10 CHAR),
	ALLOC_TIME DATE,
	SRC_LOC VARCHAR2(10 CHAR),
	DESCRIP VARCHAR2(30 CHAR),
	SPC NUMBER(4),
	PACK VARCHAR2(4 CHAR),
	PROD_SIZE VARCHAR2(6 CHAR),
	SEQ NUMBER(8),
	D_PIECES NUMBER(9),
	C_PIECES NUMBER(9),
	F_PIECES NUMBER(9),
	CUST_PO VARCHAR2(15 CHAR),
	CUST_ID VARCHAR2(10 CHAR),
	CUST_NAME VARCHAR2(30 CHAR),
	CUST_CONTACT VARCHAR2(30 CHAR),
	CUST_ADDR1 VARCHAR2(40 CHAR),
	CUST_ADDR2 VARCHAR2(40 CHAR),
	CUST_CITY VARCHAR2(20 CHAR),
	CUST_STATE VARCHAR2(2 CHAR),
	CUST_ZIP VARCHAR2(10 CHAR),
	CUST_CNTRY VARCHAR2(10 CHAR),
	CASE_LENGTH NUMBER,
	CASE_WIDTH NUMBER,
	CASE_HEIGHT NUMBER,
	CASE_CUBE NUMBER(12,4),
	SPLIT_CUBE NUMBER(7,4),
	G_WEIGHT NUMBER(8,4),
	WEIGHT NUMBER(8,4),
	CASES NUMBER,
	SPLITS NUMBER,
	COUNTRY_NAME VARCHAR2(50 CHAR),
	COUNTRY_OF_ORIGIN VARCHAR2(2 CHAR)
    )';

  END IF;
END;
/ 


DECLARE
  v_column_exists NUMBER := 0;  
BEGIN
  
  select count(*)
  into v_column_exists
  from all_objects
  where object_type = 'TYPE'
  and object_name = 'UPS_FLOAT_DTL_TAB';

  IF (v_column_exists = 0)
  THEN
    EXECUTE IMMEDIATE 'create or replace TYPE UPS_FLOAT_DTL_TAB AS TABLE of UPS_FLOAT_DTL_obj';
  END IF;
END;
/ 	