DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE owner = 'SWMS'
    and table_name = 'VENDOR_PIT_ZONE';

    IF (v_table_exists = 0)
    THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE "SWMS"."VENDOR_PIT_ZONE" 
            (	"VENDOR_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
                "ZONE_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
                CONSTRAINT "VENDOR_PK" PRIMARY KEY ("VENDOR_ID")
                USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
                TABLESPACE "SWMS_DTS2"  ENABLE
            )   
            SEGMENT CREATION DEFERRED 
                PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
                TABLESPACE "SWMS_DTS2"';

        EXECUTE IMMEDIATE 'GRANT ALL ON SWMS.VENDOR_PIT_ZONE to SWMS_USER';
        EXECUTE IMMEDIATE 'GRANT SELECT ON SWMS.VENDOR_PIT_ZONE to SWMS_VIEWER';
        EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM vendor_pit_zone for swms.vendor_pit_zone';
    END IF;
END;
/  