/********************************************************************
**
** Script to create new SWMS_FLOAT_DETAIL_IN table      
**
** Modification History:
** 
**    Date     Comments
**    -------- -------------- --------------------------------------
**    9/11/19  vkal9662 Created
*********************************************************************/
 DECLARE
    v_table_exists NUMBER := 0;
 BEGIN 
    SELECT COUNT(*)
    INTO   v_table_exists
    FROM   all_tables
    WHERE  table_name = 'SWMS_FLOAT_DETAIL_IN'
      AND  owner = 'SWMS';
              
    IF (v_table_exists = 0) THEN  
                                 
EXECUTE IMMEDIATE '    
  CREATE TABLE "SWMS"."SWMS_FLOAT_DETAIL_IN" 
   ("SEQUENCE_NUMBER" NUMBER NOT NULL ENABLE, 
	"RDC_NO" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"OPCO_NO" VARCHAR2(10 CHAR) NOT NULL ENABLE,  
	"CMU_INDICATOR" VARCHAR2(1 CHAR) NOT  NULL ENABLE, 
	"END_CUST_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CUST_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"BATCH_ID" NUMBER NOT NULL ENABLE, 
	"MASTER_ORDER_ID" VARCHAR2(25) , 
	"FLOAT_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"SEQ_NO" NUMBER(3,0) NOT NULL ENABLE, 
	"ZONE" NUMBER(2,0) NOT NULL ENABLE, 
	"STOP_NO" NUMBER(7,2) NOT NULL ENABLE, 
	"PROD_ID" VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	"SRC_LOC" VARCHAR2(10 CHAR), 
	"MULTI_HOME_SEQ" NUMBER(5,0), 
	"UOM" NUMBER(2,0), 
	"QTY_ORDER" NUMBER(9,0), 
	"QTY_ALLOC" NUMBER(9,0), 
	"MERGE_ALLOC_FLAG" VARCHAR2(1 CHAR), 
	"MERGE_LOC" VARCHAR2(10 CHAR), 
	"STATUS" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(20 CHAR), 
	"ORDER_LINE_ID" NUMBER(3,0), 
	"CUBE" NUMBER(12,4), 
	"COPY_NO" NUMBER(3,0), 
	"MERGE_FLOAT_NO" NUMBER(9,0), 
	"MERGE_SEQ_NO" NUMBER(3,0), 
	"CUST_PREF_VENDOR" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CLAM_BED_TRK" VARCHAR2(1 CHAR), 
	"ROUTE_NO" VARCHAR2(10 CHAR), 
	"ROUTE_BATCH_NO" NUMBER, 
	"ALLOC_TIME" DATE, 
	"REC_ID" VARCHAR2(12 CHAR), 
	"MFG_DATE" DATE, 
	"EXP_DATE" DATE, 
	"LOT_ID" VARCHAR2(30 CHAR), 
	"CARRIER_ID" VARCHAR2(18 CHAR), 
	"ORDER_SEQ" NUMBER(8,0), 
	"SOS_STATUS" VARCHAR2(1 CHAR), 
	"COOL_TRK" VARCHAR2(1 CHAR), 
	"CATCH_WT_TRK" VARCHAR2(1 CHAR), 
	"ITEM_SEQ" NUMBER(3,0), 
	"QTY_SHORT" NUMBER(3,0) DEFAULT 0, 
	"ST_PIECE_SEQ" NUMBER(3,0), 
	"SELECTOR_ID" VARCHAR2(10 CHAR), 
	"BC_ST_PIECE_SEQ" NUMBER(3,0), 
	"SHORT_ITEM_SEQ" NUMBER(4,0), 
	"RESIDUAL_QTY" NUMBER(9,0), 
	"RDC_OUTBOUND_CHILD_PALLET_ID" VARCHAR2(18 CHAR), 
	"WH_OUT_QTY" NUMBER(7,0), 
	"REASON_CD" VARCHAR2(3 CHAR), 
	"LABOR_BATCH_NO" VARCHAR2(13 CHAR), 
	"RECORD_STATUS" VARCHAR2(1 CHAR) DEFAULT ''N'' NOT NULL ENABLE, 
	"ERROR_MSG" VARCHAR2(250 CHAR), 
	"ADD_USER" VARCHAR2(30 CHAR) DEFAULT REPLACE( USER, ''OPS$'' ), 
	"ADD_DATE" DATE DEFAULT SYSDATE, 
	"UPD_USER" VARCHAR2(30 CHAR), 
	"UPD_DATE" DATE
   ) ';
        
	EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM SWMS_FLOAT_DETAIL_IN FOR SWMS.SWMS_FLOAT_DETAIL_IN';

	EXECUTE IMMEDIATE 'GRANT DELETE, INSERT, SELECT, UPDATE ON SWMS.SWMS_FLOAT_DETAIL_IN TO SWMS_USER';
        
	EXECUTE IMMEDIATE 'GRANT SELECT ON SWMS.SWMS_FLOAT_DETAIL_IN TO SWMS_VIEWER';   
  
END IF;      
END;
/
